In [1]:
%load_ext autoreload
%autoreload 2

from paper_utils import *
    
import os
# os.chdir('../..')
from sklearn.metrics import cohen_kappa_score

# Print entailment inputs for human rating

In [ ]:
runs = {
    '1r6kekju': 'squad-deberta',
    'f8yk94fy': 'trivia_qa-deberta',
    'lzlhybwt': 'bioasq-deberta',
}

configs = {}
for wandb_id in runs:
    configs[wandb_id] = restore_file(wandb_id, filenames=['config.yaml'])[0]
    
check_first_item(configs)

```
contradiction -> 0
neutral -> 1
entailment -> 2
```

In [286]:
def print4human(wandbid, MAX_NO=100, SKIP_UNTIL=0):

    name = runs[wandbid]
    model = '-'.join(name.split('-')[1:])
    slurmid = api.run(f'goatml/semantic_uncertainty/{wandbid}').notes.split(': ')[1]
    last_question = ''
    entailment_counter = 0
    entailment_preds = {}
    skip = False
    
    
    with open(f'../../log/slurm-{slurmid}.out', 'r') as f:
        lines = f.readlines()
        for i, line in enumerate(lines):
            if 'INFO' in line:
                line = line[line.index('INFO') + len('INFO') + 4:]
    
            if f'{model} input:'.lower() in line.lower():
    
                original_line = line
    
                if model == 'deberta':
                    if 'weight room' in line:
                        line = 'How many weight rooms are in the Malkin Athletic Center'
                    elif '?' in line:
                        line = line[:line.index('?')]
                    elif '.' in line[:50]:
                        line = line[:line.index('.')]
                    else:
                        line = line[:40]
                
                if line == last_question:
                    skip = True
                    continue
                else:
                    print(entailment_counter, original_line)
                    skip = False
    
                last_question = line
                entailment_counter += 1
            
            sys.stdout.flush()
            if entailment_counter == MAX_NO:
                break

In [283]:
# squad
print4human('1r6kekju')

0  Deberta Input: What was Warsaw's population in 1901? According to the census of 1901, Warsaw's population was 756,475. -> What was Warsaw's population in 1901? According to the census of 1901, Warsaw's population was 817,000.

1  Deberta Input: When did O2 begin to acculturate in the atmosphere? O2 began to accumulate in the atmosphere approximately 2.7 billion years ago during the Great Oxygenation Event. -> When did O2 begin to acculturate in the atmosphere? Oxygen began to accumulate in the atmosphere around 2.7 billion years ago during the Great Oxygenation Event.

2  Deberta Input: Who was Frédéric Chopin? Frédéric Chopin was a Polish-French Romantic composer and pianist known for his delicate, expressive, and technically demanding piano music. -> Who was Frédéric Chopin? Frédéric Chopin was a Polish composer and pianist of the Romantic era who is widely regarded as one of the greatest composers of all time, known for his technically demanding and expressive piano music, including nocturnes, waltzes, preludes, and sonatas.

3  Deberta Input: Harvard - Yale Regatta predates "The Game" by how many years? The Harvard-Yale Regatta predates "The Game" by 24 years, with the first regatta taking place in 1852 and the first football game between the two schools being played in 1875. -> Harvard - Yale Regatta predates "The Game" by how many years? The Harvard-Yale Regatta predates "The Game" by 21 years, with the first regatta held in 1852 and the first football game played in 1875.

4  Deberta Input: Where did Moncalm slip away to attack, left largely unprotected? Moncalm slipped away to attack the British left flank, which was left largely unprotected. -> Where did Moncalm slip away to attack, left largely unprotected? Moncalm slipped away to attack the largely unprotected British right flank.

5  Deberta Input: Indigenous territories are largely being destroyed in what two ways? Indigenous territories are being largely destroyed by both the physical appropriation of their lands for resource extraction, infrastructure, and settlements, and by the legal and political marginalization of Indigenous peoples, which denies them control over their own lands and resources. -> Indigenous territories are largely being destroyed in what two ways? Indigenous territories are being largely destroyed through the exploitation of their natural resources and the forced assimilation of indigenous peoples.

6  Deberta Input: When did the British defeat New France? The British defeated New France in 1763, following the French and Indian War. -> When did the British defeat New France? The British defeated New France in 1763, following the French and Indian War.

7  Deberta Input: Drop in the blood levels of cortisol and epinephrine results in increase levels of what hormones? A drop in blood levels of cortisol and epinephrine results in increased levels of insulin. -> Drop in the blood levels of cortisol and epinephrine results in increase levels of what hormones? Drop in the blood levels of cortisol and epinephrine results in increase levels of insulin and growth hormone.

8  Deberta Input: When was the military-political complex reflected upon within the scope of understanding imperialism? The military-political complex was reflected upon within the scope of understanding imperialism during the 1960s and 1970s, particularly in the work of scholars such as Chalmers Johnson and Edward Said, who argued that military power and political dominance were closely linked with economic interests and cultural domination in the context of imperialism. -> When was the military-political complex reflected upon within the scope of understanding imperialism? The military-political complex was reflected upon within the scope of understanding imperialism in the 1960s and 1970s by scholars such as Chalmers Johnson, who argued that the complex was a key driver of US imperialism and that its influence had become increasingly pervasive in American society.

9  Deberta Input: What kind of division of power did Kublai's government have? The government of Kublai Khan had a tripartite division of power between the emperor, the chancellor, and the military leaders, with the emperor holding supreme power but relying on the chancellor and military leaders to administer and enforce his rule. -> What kind of division of power did Kublai's government have? Kublai's government had a centralized division of power, with the emperor holding supreme authority and appointing officials to govern the various regions of the empire.

10  Deberta Input: What church in Virginia is maintained by Huguenots as a historic shrine? The Huguenot Church in Manakin-Sabot, Virginia, is maintained by Huguenots as a historic shrine. -> What church in Virginia is maintained by Huguenots as a historic shrine? The Huguenot Church in Manakin-Sabot, Virginia, is maintained by Huguenots as a historic shrine.

11  Deberta Input: After 1935, who would be forbidden to enter Rhineland? The Treaty of Versailles, which had established Rhineland as a demilitarized zone, was violated by Germany when they marched their military into the region in 1936, and after that, Jews were forbidden to enter Rhineland. -> After 1935, who would be forbidden to enter Rhineland? The Treaty of Versailles and the subsequent agreements of 1925 and 1934, prohibited Germany from stationing military forces in the Rhineland, and after 1935, any military forces other than those of the League of Nations.

12  Deberta Input: How many residents were recorded in the 2010 census of Jacksonville? According to the 2010 census, Jacksonville had a population of approximately 821,785 residents. -> How many residents were recorded in the 2010 census of Jacksonville? According to the 2010 census, the population of Jacksonville was 821,784.

13  Deberta Input: What  former administrative building was used for the MSP's offices? The MSP's offices were located in the former Michigan Bell and Western Union Building. -> What  former administrative building was used for the MSP's offices? The MSP's offices were located in the former Detroit Public Schools' headquarters building.

14  Deberta Input: A satellite that measured the amount of dust going to the Amazon was named what? The satellite that measured the amount of dust going to the Amazon was named "Earth." -> A satellite that measured the amount of dust going to the Amazon was named what? The satellite that measured the amount of dust going to the Amazon was named OMI (Ozone Monitoring Instrument).

15  Deberta Input: What percent of untreated victims of the plague die within 8 days? Sixty to ninety percent of untreated victims of the plague die within 8 days. -> What percent of untreated victims of the plague die within 8 days? Approximately 60% of untreated victims of the plague die within 8 days.

16  Deberta Input: Who studies the expected monetary flow over the life of the project and to monitor the payouts throughout the process? The financial analyst is responsible for studying the expected monetary flow over the life of the project and monitoring the payouts throughout the process. -> Who studies the expected monetary flow over the life of the project and to monitor the payouts throughout the process? A financial analyst studies the expected monetary flow over the life of the project and monitors the payouts throughout the process.

17  Deberta Input: What did Alec Shelbrooke propose payments of benefits to be made on? Alec Shelbrooke proposed that payments of benefits be made on a slimmed-down, means-tested basis, taking into account only the claimant's income and savings, but not their spare bedrooms or other assets. -> What did Alec Shelbrooke propose payments of benefits to be made on? Alec Shelbrooke proposed that payments of benefits be made on a Universal Credit system, where all benefits would be combined into a single payment.

18  Deberta Input: For each of the 28 member states, how many Commissioner's are represented for each one? Each of the 28 member states of the European Union has one Commissioner representing them in the European Commission, for a total of 28 Commissioners. -> For each of the 28 member states, how many Commissioner's are represented for each one? Each of the 28 member states of the European Union has one Commissioner representing them in the European Commission.

19  Deberta Input: How many people did the Islamic State control the territory of as of March 2015? As of March 2015, the Islamic State controlled the territory of approximately 9 million people, primarily in Iraq and Syria. -> How many people did the Islamic State control the territory of as of March 2015? As of March 2015, the Islamic State controlled the territory of approximately 9 million people, primarily in Iraq and Syria, but also in smaller areas of Libya, Egypt, and Yemen.

20  Deberta Input: What is the section of the Rhine Gorge recognized by UNESCO called? The section of the Rhine Gorge recognized by UNESCO is called the "Upper Middle Rhine Valley" or "Oberes Mittelrheintal" in German. -> What is the section of the Rhine Gorge recognized by UNESCO called? The section of the Rhine Gorge recognized by UNESCO is called the Upper Middle Rhine Valley.

21  Deberta Input: What is one straightforward case of a probabilistic test? A straightforward case of a probabilistic test is a coin flip, where the probability of heads or tails is 0.5, and the outcome is determined by chance. -> What is one straightforward case of a probabilistic test? One straightforward case of a probabilistic test is a coin flip, where the outcome of heads or tails is equally likely and can be modeled by a Bernoulli distribution.

22  Deberta Input: What is responsible for constraining P according to the time hierarchy theorem? The time hierarchy theorem states that P is constrained by the logarithmic time hierarchy, which means that the time complexity of algorithms in P increases logarithmically with the size of the input. -> What is responsible for constraining P according to the time hierarchy theorem? According to the time hierarchy theorem, P is constrained by the time required to solve a problem of a certain size.

23  Deberta Input: Where was Victoria first set to be located in Australia? Victoria was first set to be located in Australia at Port Phillip Bay, which was later named Melbourne. -> Where was Victoria first set to be located in Australia? Victoria was first set to be located in Australia at Port Phillip Bay, which was chosen by Captain James Cook in 1770 as a suitable site for a British colony.

24  Deberta Input: In order to be considered in the top percentile, a person would need to amass how much money each year? According to the data, a person would need to amass approximately $1.5 million per year to be considered in the top 1% of earners. -> In order to be considered in the top percentile, a person would need to amass how much money each year? A person would need to amass around $300,000 each year to be considered in the top 1% of earners in the United States.

25  Deberta Input: What evidence between and among complexity classes would signify a theoretical watershed for complexity theory? A proof that NP is equal to P, or a proof that NP is strictly larger than P, would signify a theoretical watershed for complexity theory, as it would either establish a fundamental limit on the efficiency of algorithms or provide a new basis for efficient computation, respectively. -> What evidence between and among complexity classes would signify a theoretical watershed for complexity theory? Evidence of a non-relational algorithm that can solve an NP-complete problem in polynomial time would signify a theoretical watershed for complexity theory, as it would establish a new paradigm for efficient computation and challenge the fundamental assumptions underlying the field.

26  Deberta Input: Whose thesis states that the solution to a problem is solvable with reasonable resources assuming it allows for a polynomial time algorithm? Stephen Cook's thesis states that the solution to a problem is solvable with reasonable resources assuming it allows for a polynomial time algorithm. -> Whose thesis states that the solution to a problem is solvable with reasonable resources assuming it allows for a polynomial time algorithm? Stephen Cook's thesis states that the solution to a problem is solvable with reasonable resources assuming it allows for a polynomial time algorithm.

27  Deberta Input: When did Warsaw become the center of the Congress Poland? Warsaw became the center of the Congress Poland in 1815, when the Congress of Vienna established the Duchy of Warsaw as a sovereign state under the rule of the Russian Empire. -> When did Warsaw become the center of the Congress Poland? Warsaw became the center of the Congress Poland in 1815, when the Congress of Vienna established the Duchy of Warsaw as a sovereign state under the rule of the Russian Empire.

28  Deberta Input: How long does it take for the effects to manifest as changes to economic growth? The effects of climate change on economic growth can manifest in various ways, including reduced productivity, loss of infrastructure, and increased costs for health care and emergency response, and these effects can begin to manifest within a few years or even months of the onset of climate-related events, such as heatwaves, droughts, or storms. -> How long does it take for the effects to manifest as changes to economic growth? The effects of climate change on economic growth can manifest in various timeframes, but recent studies suggest that the impacts are already being felt and will continue to intensify over the next few decades, with potentially significant reductions in global economic output by 2100.

29  Deberta Input: What was the goal of this Roman disobedience? The goal of the Roman disobedience was to gain independence from British rule and to establish a democratic government that would respect the rights and freedoms of the Indian people. -> What was the goal of this Roman disobedience? The goal of the Roman disobedience was to openly defy God's law and assert their own autonomy and independence from divine authority, driven by a desire to be like God and determine their own morality.

30  Deberta Input: When did the Wahhabi seized the Grand Mosque in Mecca? The Wahhabi seized the Grand Mosque in Mecca in 1802. -> When did the Wahhabi seized the Grand Mosque in Mecca? The Wahhabi seized the Grand Mosque in Mecca on November 20, 1979.

31  Deberta Input: Other than the San Jacinto Fault, and the Elsinore Fault, name one other fault. The San Andreas Fault. -> Other than the San Jacinto Fault, and the Elsinore Fault, name one other fault. The Whittier Fault.

32  Deberta Input: Who is usually working together? Team members are usually working together. -> Who is usually working together? Family members and coworkers are usually working together.

33  Deberta Input: What country uses the Bowl of Hygieia as a symbol of pharmacy? The Bowl of Hygieia is used as a symbol of pharmacy in the United States. -> What country uses the Bowl of Hygieia as a symbol of pharmacy? The Bowl of Hygieia is a symbol of pharmacy in Greece.

34  Deberta Input: Who called for an agency to be created to be solely focused at undermining the Islamism ideology? The U.S. Army Lieutenant General H.R. McMaster. -> Who called for an agency to be created to be solely focused at undermining the Islamism ideology? The idea of creating an agency dedicated to countering Islamism was first proposed by Jordanian King Abdullah II in a 2004 letter to President George W. Bush.

35  Deberta Input: Which arts were often practiced together by the same artists? Painting, sculpture, and architecture were often practiced together by the same artists during the Renaissance. -> Which arts were often practiced together by the same artists? Painting and sculpture were often practiced together by the same artists in ancient Greece, as many sculptors also painted and vice versa.

36  Deberta Input: Why did OPEC raise the price of oil to $5.11? OPEC raised the price of oil to $5.11 because they wanted to increase their profit margins and gain more economic power. -> Why did OPEC raise the price of oil to $5.11? OPEC raised the price of oil to $5.11 per barrel in 1973 in response to the US decision to support Israel in the Yom Kippur War, sparking an oil embargo that led to a sharp increase in global oil prices.

37  Deberta Input: What is the term given to algorithms that utilize random bits? Algorithms that utilize random bits are called "randomized algorithms." -> What is the term given to algorithms that utilize random bits? The term given to algorithms that utilize random bits is "randomized algorithms."

38  Deberta Input: Which entity focused upon the free movement of workers? The International Labor Organization (ILO) focused upon the free movement of workers. -> Which entity focused upon the free movement of workers? The International Labor Organization (ILO) focused upon the free movement of workers.

39  Deberta Input: What was the first steam powered device used commercially? The first steam powered device used commercially was the steam engine, which was invented by James Watt in 1765 and was first used in a cotton mill in 1781. -> What was the first steam powered device used commercially? The first steam powered device used commercially was the steam engine, which was invented by James Watt in 1769 and was first used in a cotton mill in 1781.

40  Deberta Input: When was the study on sequenced Y genomes published? The study on sequenced Y genomes was published in 2014. -> When was the study on sequenced Y genomes published? The study on sequenced Y genomes was published in 2014.

41  Deberta Input: When did the UK formally subscribe to the Agreement on Social Policy? The UK formally subscribed to the Agreement on Social Policy on 13 November 2000. -> When did the UK formally subscribe to the Agreement on Social Policy? The UK formally subscribed to the Agreement on Social Policy in 1992.

42  Deberta Input: Where do platycenida live? Platycenida are marine animals that live in warm, shallow waters around the world, typically inhabiting coral reefs, rocky crevices, and sandy bottoms. -> Where do platycenida live? Platycenida are found in marine environments, typically inhabiting shallow-water areas with rocky substrates, coral reefs, and algal-covered rocks.

43  Deberta Input: Which species moves by a darting motion? The nematode worm moves by a darting motion. -> Which species moves by a darting motion? The species that moves by a darting motion is the clownfish.

44  Deberta Input: How many weight rooms are in the Malkin Athletic Center There are 3 weight rooms in the Malkin Athletic Center. -> How many weight rooms are in the Malkin Athletic Center The Malkin Athletic Center has three weight rooms.

45  Deberta Input: Who did the attacks resonate most with? The attacks resonated most with the group that perpetrated them, the Islamic extremist organization Al-Qaeda, who saw the attacks as a means of drawing attention to their cause and inflicting harm on their enemies. -> Who did the attacks resonate most with? The attacks resonated most with the American public, particularly those who were directly affected by the events, including the families of the victims, survivors, and first responders.

46  Deberta Input: How was the Dutch name for the Rhine originally spelled?  The Dutch name for the Rhine was originally spelled "Rijn" but it has undergone several changes in spelling over the centuries, and today it is commonly spelled "Rijnt" in modern Dutch. -> How was the Dutch name for the Rhine originally spelled?  The Dutch name for the Rhine was originally spelled "Rijn" in the Middle Ages, although it has evolved over time and is now commonly spelled "Rijne" in modern Dutch.


In [287]:
# trivia-qa
print4human('f8yk94fy')

0  Deberta Input: Nigel Hawthorne was Oscar nominated for The Madness of which King? Nigel Hawthorne was Oscar nominated for The Madness of King George. -> Nigel Hawthorne was Oscar nominated for The Madness of which King? Nigel Hawthorne was Oscar-nominated for his portrayal of King George III in The Madness of King George.

1  Deberta Input: Which actress and singer's biography was entitled 'The Other Side Of The Rainbow'? Judy Garland's biography was entitled 'The Other Side Of The Rainbow'. -> Which actress and singer's biography was entitled 'The Other Side Of The Rainbow'? The actress and singer whose biography was entitled 'The Other Side Of The Rainbow' was Judy Garland.

2  Deberta Input: The actor John Wayne was known by what nickname? John Wayne was known by the nickname "The Duke." -> The actor John Wayne was known by what nickname? The actor John Wayne was known by the nickname "The Duke."

3  Deberta Input: In Greek mythology, who did flute playing shepherd Marsyas challenge to a music contest, the winner of which flayed Marsyas to death for his presumption? In Greek mythology, flute playing shepherd Marsyas challenged Apollo, the god of music, to a music contest, the winner of which, Apollo, flayed Marsyas to death for his presumption. -> In Greek mythology, who did flute playing shepherd Marsyas challenge to a music contest, the winner of which flayed Marsyas to death for his presumption? In Greek mythology, flute playing shepherd Marsyas challenged Apollo, the god of music, to a music contest, and was defeated and flayed to death for his presumption.

4  Deberta Input: The musical ‘Half a Sixpence’ was based on which 1905 novel? The musical ‘Half a Sixpence’ was based on the 1905 novel “Kipps: The Story of a Simple Soul” by H.G. Wells. -> The musical ‘Half a Sixpence’ was based on which 1905 novel? The musical ‘Half a Sixpence’ was based on the 1905 novel "Kipps: The Story of a Simple Soul" by H.G. Wells.

5  Deberta Input: The Bledisloe Cup is contested by Australia and New Zealand in which sport? The Bledisloe Cup is contested by Australia and New Zealand in rugby union. -> The Bledisloe Cup is contested by Australia and New Zealand in which sport? The Bledisloe Cup is contested by Australia and New Zealand in rugby union.

6  Deberta Input: James Esdaile, John Elliotson, Jean-Martin Charcot, Hippolyte Bernheim, Pierre Janet, mile Cou, Morton Prince, Clark L. Hull, Andrew Salter, Theodore R. Sarbin, Ernest Hilgard, Martin Theodore Orne, and Nicholas Spanos are associated with what? The study of hypnosis. -> James Esdaile, John Elliotson, Jean-Martin Charcot, Hippolyte Bernheim, Pierre Janet, mile Cou, Morton Prince, Clark L. Hull, Andrew Salter, Theodore R. Sarbin, Ernest Hilgard, Martin Theodore Orne, and Nicholas Spanos are associated with what? These men are all influential figures in the history and development of hypnosis and hypnotherapy.

7  Deberta Input: Mary Surratt was executed having been found guilty of the conspiracy to assassinate who? Mary Surratt was executed having been found guilty of the conspiracy to assassinate President Abraham Lincoln. -> Mary Surratt was executed having been found guilty of the conspiracy to assassinate who? Mary Surratt was executed having been found guilty of the conspiracy to assassinate President Abraham Lincoln.

8  Deberta Input: In which athletics event has the Fosbury Flop been much adopted since 1968 ? The Fosbury Flop has been much adopted in the high jump event in athletics since 1968. -> In which athletics event has the Fosbury Flop been much adopted since 1968 ? The Fosbury Flop has been much adopted in the high jump event in athletics since 1968.

9  Deberta Input: The inaugural issue of what comic book, which was released in June, 1938, introduced Superman? The inaugural issue of Action Comics, which was released in June, 1938, introduced Superman. -> The inaugural issue of what comic book, which was released in June, 1938, introduced Superman? The inaugural issue of Action Comics, which was released in June, 1938, introduced Superman.

10  Deberta Input: In which London building do you find the Jerusalem Chamber? The Jerusalem Chamber is located in the palace of Westminster. -> In which London building do you find the Jerusalem Chamber? The Jerusalem Chamber is located in the Palace of Westminster.

11  Deberta Input: How is the tree Fraxinus excelsior more commonly known? The tree Fraxinus excelsior is more commonly known as the ash tree. -> How is the tree Fraxinus excelsior more commonly known? The tree Fraxinus excelsior is more commonly known as the ash tree.

12  Deberta Input: What is the spiked stick or prod used for driving cattle called? The spiked stick or prod used for driving cattle is called a "cowprod" or "stockwhip." -> What is the spiked stick or prod used for driving cattle called? The spiked stick or prod used for driving cattle is called a "cattle prod" or "stock prod."

13  Deberta Input: Who wrote the Mott The Hoople hit 'All The Young Dudes'? David Bowie wrote the Mott The Hoople hit 'All The Young Dudes'. -> Who wrote the Mott The Hoople hit 'All The Young Dudes'? David Bowie wrote the Mott The Hoople hit 'All The Young Dudes'.

14  Deberta Input: In which country was Earl Spencer's acrimonious divorce settlement heard? Earl Spencer's acrimonious divorce settlement was heard in England. -> In which country was Earl Spencer's acrimonious divorce settlement heard? Earl Spencer's acrimonious divorce settlement was heard in the United Kingdom.

15  Deberta Input: In which of Thomas Hardy's novels is Bathsheba Everdene the heroine? Bathsheba Everdene is the heroine of Thomas Hardy's novel "Far from the Madding Crowd". -> In which of Thomas Hardy's novels is Bathsheba Everdene the heroine? Bathsheba Everdene is the heroine of Thomas Hardy's novel "Far from the Madding Crowd."

16  Deberta Input: What type of scenes was Dame Laura Knight noted for painting Dame Laura Knight was noted for painting scenes of everyday life, often capturing the spirit and energy of the modern world, as well as landscapes and portraits. -> What type of scenes was Dame Laura Knight noted for painting Dame Laura Knight was noted for painting scenes of theatrical performances, circuses, and everyday life in the 1920s and 1930s, often capturing the glamour and spectacle of urban life in her works.

17  Deberta Input: A 2 stroke engine, used in such devices as chainsaws, is fuelled by a mixture of petrol and what other liquid? A 2 stroke engine, used in such devices as chainsaws, is fuelled by a mixture of petrol and oil. -> A 2 stroke engine, used in such devices as chainsaws, is fuelled by a mixture of petrol and what other liquid? A 2 stroke engine, used in such devices as chainsaws, is fuelled by a mixture of petrol and oil.

18  Deberta Input: Mount Entoto is the highest peak overlooking which African capital city? Mount Entoto is the highest peak overlooking Addis Ababa, the capital city of Ethiopia. -> Mount Entoto is the highest peak overlooking which African capital city? Mount Entoto is the highest peak overlooking the capital city of Addis Ababa, Ethiopia.

19  Deberta Input: In which year was the Juilliard School founded in New York? The Juilliard School was founded in 1905 as the Institute of Musical Art in New York. -> In which year was the Juilliard School founded in New York? The Juilliard School was founded in 1905 as the Institute of Musical Art in New York.

20  Deberta Input: Who wrote the play, 'A Day In The Death Of Joe Egg'? The play, 'A Day In The Death Of Joe Egg', was written by Peter Nichols. -> Who wrote the play, 'A Day In The Death Of Joe Egg'? The play, 'A Day In The Death Of Joe Egg', was written by Peter Nichols.

21  Deberta Input: What is the screen name of the actor Bernard Schwarz? Bernard Schwarz's screen name is Arnold Schwarzenegger. -> What is the screen name of the actor Bernard Schwarz? The screen name of the actor Bernard Schwarz is Arnold Schwarzenegger.

22  Deberta Input: Which 1976 Nobel laureate popularised Monetarist theory? Milton Friedman, who was awarded the Nobel Memorial Prize in Economic Sciences in 1976, popularized Monetarist theory through his influential book "A Monetary History of the United States" and his advocacy for free market principles. -> Which 1976 Nobel laureate popularised Monetarist theory? Milton Friedman popularised Monetarist theory in his 1976 book, "A Monetary History of the United States".

23  Deberta Input: In the culinary world, what word is used for the edible offal of a fowl, typically including the heart, gizzard and liver? Giblets. -> In the culinary world, what word is used for the edible offal of a fowl, typically including the heart, gizzard and liver? Giblets.

24  Deberta Input: Who wrote the book 'Elmer Gantry'? The book 'Elmer Gantry' was written by Sinclair Lewis. -> Who wrote the book 'Elmer Gantry'? Sinclair Lewis.

25  Deberta Input: Which country used to be called Southern Rhodesia? The country that used to be called Southern Rhodesia is now known as Zimbabwe. -> Which country used to be called Southern Rhodesia? The country that used to be called Southern Rhodesia is now known as Zimbabwe.

26  Deberta Input: Eleanor of Provence was the wife of which long-reigning English king? Eleanor of Provence was the wife of King Henry III of England. -> Eleanor of Provence was the wife of which long-reigning English king? Eleanor of Provence was the wife of King Henry III of England, who ruled from 1216 to 1272.

27  Deberta Input: What writer was convicted of sodomy and sentenced to hard labor? Oscar Wilde. -> What writer was convicted of sodomy and sentenced to hard labor? Oscar Wilde.

28  Deberta Input: "Meaning ""double step” in Spanish, which dance actually originated in southern France but is modelled after the sound, drama, and movement of the Spanish bullfight?" The dance that originated in southern France but is modelled after the sound, drama, and movement of the Spanish bullfight is the paso doble. -> "Meaning ""double step” in Spanish, which dance actually originated in southern France but is modelled after the sound, drama, and movement of the Spanish bullfight?" The paso doble.

29  Deberta Input: Who is featured on Puff Daddy's Can't Hold Me Down? The Notorious B.I.G. is featured on Puff Daddy's Can't Hold Me Down. -> Who is featured on Puff Daddy's Can't Hold Me Down? Mase is featured on Puff Daddy's Can't Hold Me Down.

30  Deberta Input: Whose birthday is celebrated by a public holiday on the third Monday in January in the USA? The birthday of Martin Luther King Jr. is celebrated by a public holiday on the third Monday in January in the USA. -> Whose birthday is celebrated by a public holiday on the third Monday in January in the USA? Martin Luther King Jr.'s birthday is celebrated by a public holiday on the third Monday in January in the USA.

31  Deberta Input: Composite, Shield and Cinder Cone are all types of what? Volcanoes. -> Composite, Shield and Cinder Cone are all types of what? Volcanoes.

32  Deberta Input: In which US town or city were the 1932 Winter Olympics held? The 1932 Winter Olympics were held in Lake Placid, New York. -> In which US town or city were the 1932 Winter Olympics held? The 1932 Winter Olympics were held in Lake Placid, New York, USA.

33  Deberta Input: A 2 stroke engine, used in such devices as chainsaws, is fuelled by a mixture of petrol and what other liquid? A 2 stroke engine, used in such devices as chainsaws, is fuelled by a mixture of petrol and oil. -> A 2 stroke engine, used in such devices as chainsaws, is fuelled by a mixture of petrol and what other liquid? A 2 stroke engine, used in such devices as chainsaws, is fuelled by a mixture of petrol and oil.

34  Deberta Input: Can you name the singer of the title track for '1997 - Tomorrow Never Dies'? The singer of the title track for '1997 - Tomorrow Never Dies' is Shirley Manson. -> Can you name the singer of the title track for '1997 - Tomorrow Never Dies'? Sheryl Crow sang the title track for the 1997 James Bond film 'Tomorrow Never Dies'.

35  Deberta Input: Antananarivo is the capital of which country? Antananarivo is the capital of Madagascar. -> Antananarivo is the capital of which country? Antananarivo is the capital of Madagascar.

36  Deberta Input: What was the surname of the 19th president of the USA who had the first christian name Rutherford ? The surname of the 19th president of the USA who had the first Christian name Rutherford was Hayes. -> What was the surname of the 19th president of the USA who had the first christian name Rutherford ? Hayes.

37  Deberta Input: What was the name of the company that 'Reginald Perrin' worked for in 'The Fall and Rise of Reginald Perrin'? The company that Reginald Perrin worked for in 'The Fall and Rise of Reginald Perrin' was called Sunshine Desserts. -> What was the name of the company that 'Reginald Perrin' worked for in 'The Fall and Rise of Reginald Perrin'? Sunshine Desserts.

38  Deberta Input: In which country is Dubrovnik? Dubrovnik is in Croatia. -> In which country is Dubrovnik? Dubrovnik is located in Croatia.

39  Deberta Input: In Greek mythology, what was the name of the nymphs who tended the garden from where Heracles stole golden apples? The nymphs who tended the garden from where Heracles stole golden apples were called the Hesperides. -> In Greek mythology, what was the name of the nymphs who tended the garden from where Heracles stole golden apples? The nymphs who tended the garden from where Heracles stole golden apples were called the Hesperides.

40  Deberta Input: Name the UK budget holiday company specialising in Turkey and Greece which went bust in July 2010? Sunspot Tours. -> Name the UK budget holiday company specialising in Turkey and Greece which went bust in July 2010? The UK budget holiday company specialising in Turkey and Greece that went bust in July 2010 was Airtours.

41  Deberta Input: In which sport would you see someone slam-dunking the ball? Basketball. -> In which sport would you see someone slam-dunking the ball? Basketball.

42  Deberta Input: What is the name of the female alter-ego of Turner Prize winner Grayson perry? The female alter-ego of Turner Prize winner Grayson Perry is Claire. -> What is the name of the female alter-ego of Turner Prize winner Grayson perry? The female alter-ego of Turner Prize winner Grayson Perry is Claire Perry.

43  Deberta Input: Broxtowe District Council is in which English county? Broxtowe District Council is in Nottinghamshire. -> Broxtowe District Council is in which English county? Broxtowe District Council is in Nottinghamshire, England.

44  Deberta Input: "In 2006 English politician George Galloway was widely quoted as saying that it would be ""morally justified if someone chose to assassinate "" whom?" George Galloway was widely quoted as saying that it would be morally justified if someone chose to assassinate Tony Blair. -> "In 2006 English politician George Galloway was widely quoted as saying that it would be ""morally justified if someone chose to assassinate "" whom?" George Galloway was widely quoted as saying that it would be morally justified if someone chose to assassinate Tony Blair.

45  Deberta Input: "Which pop group originally called ""Garden Wall"" changed their name when it was said they were ""Born"" their first top ten hit was ""Follow you Follow me"" in 1978?" The pop group originally called "Garden Wall" that changed their name and had their first top ten hit with "Follow You Follow Me" in 1978 was Genesis. -> "Which pop group originally called ""Garden Wall"" changed their name when it was said they were ""Born"" their first top ten hit was ""Follow you Follow me"" in 1978?" The pop group that originally called themselves "Garden Wall" and changed their name when they were said to be "Born" and had their first top ten hit with "Follow You Follow Me" in 1978 was Genesis.

46  Deberta Input: Which playing card is called the curse of Scotland The nine of diamonds is sometimes called the curse of Scotland. -> Which playing card is called the curse of Scotland The Nine of Diamonds is called the curse of Scotland.

47  Deberta Input: In Greek mythology who was the twin of Polydeuces? Castor was the twin of Polydeuces. -> In Greek mythology who was the twin of Polydeuces? Castor was the twin of Polydeuces.

48  Deberta Input: On whose life is Somerset Maugham's 'The Moon and Sixpence' loosely based? Somerset Maugham's 'The Moon and Sixpence' is loosely based on the life of Paul Gauguin. -> On whose life is Somerset Maugham's 'The Moon and Sixpence' loosely based? The life of Paul Gauguin.

49  Deberta Input: Which organisation was founded in 1863 after the publication of the book 'A Memory Of Solferino' by the Swiss businessman Henri Dunant? The International Committee of the Red Cross (ICRC) was founded in 1863 after the publication of the book 'A Memory Of Solferino' by the Swiss businessman Henri Dunant. -> Which organisation was founded in 1863 after the publication of the book 'A Memory Of Solferino' by the Swiss businessman Henri Dunant? The International Committee of the Red Cross was founded in 1863 after the publication of the book 'A Memory Of Solferino' by the Swiss businessman Henri Dunant.

50  Deberta Input: In the 2015 MTV awards who was voted as the best male act Ed Sheeran won the award for Best Male Act at the 2015 MTV European Music Awards. -> In the 2015 MTV awards who was voted as the best male act In the 2015 MTV awards, Ed Sheeran was voted as the best male act.

51  Deberta Input: The German's called it the Siegfried Line, what did the allies call it? The Allies called the German defensive line the "Westwall" or "Siegfried Line." -> The German's called it the Siegfried Line, what did the allies call it? The Allies called it the "Westwall" or "Siegfried Line" as well, but also referred to it as the "Dragon's Teeth" or the "Shutzwall" (Protective Wall).

52  Deberta Input: What British army bugle call used at funerals originally signalled the end of the military day after final inspection? The British army bugle call used at funerals that originally signaled the end of the military day after final inspection is "The Last Post." -> What British army bugle call used at funerals originally signalled the end of the military day after final inspection? The Last Post.

53  Deberta Input: What type of exhibit can be seen in the military museum at Bovington in Dorset? The military museum at Bovington in Dorset features a collection of armoured vehicles, including tanks, armoured cars, and personnel carriers, as well as related artifacts and memorabilia. -> What type of exhibit can be seen in the military museum at Bovington in Dorset? The military museum at Bovington in Dorset features a collection of tanks and armoured vehicles, including the first tank to enter combat, the Mark I, as well as other military vehicles, weapons, and memorabilia.

54  Deberta Input: What was the Elephant Man's real name? The Elephant Man's real name was Joseph Merrick. -> What was the Elephant Man's real name? The Elephant Man's real name was Joseph Merrick.

55  Deberta Input: Which canal is known as the 'Highway to India'? The Suez Canal is known as the "Highway to India" as it provides a vital waterway for trade and transportation between Europe and Asia, particularly for goods and people traveling between the Mediterranean region and the Indian subcontinent. -> Which canal is known as the 'Highway to India'? The Suez Canal is commonly referred to as the 'Highway to India' due to its role in connecting Europe to Asia and facilitating trade between the two continents.


In [288]:
# bioasq
print4human('lzlhybwt')

0  Deberta Input: Computational tools for predicting allosteric pathways in proteins Computational tools for predicting allosteric pathways in proteins include molecular dynamics simulations, molecular docking, machine learning algorithms, and structure-based design methods. -> Computational tools for predicting allosteric pathways in proteins Computational tools for predicting allosteric pathways in proteins include molecular dynamics simulations, structure-based modeling, machine learning algorithms, and graph theory-based methods, which can aid in identifying potential allosteric sites, predicting the binding of small molecules or protein ligands, and understanding the underlying mechanisms of allostery.

1  Deberta Input: Which is the molecular mechanism underlying K-ras alterations in carcinomas? K-ras alterations in carcinomas involve mutations in the KRAS gene, which can result in the production of a constitutively active K-ras protein that promotes cell proliferation and survival, even in the absence of upstream signals. -> Which is the molecular mechanism underlying K-ras alterations in carcinomas? The molecular mechanism underlying K-ras alterations in carcinomas is a point mutation in the K-ras gene that results in the substitution of a glutamine residue for a glutamic acid residue at position 61, leading to the activation of downstream signaling pathways and uncontrolled cell proliferation.

2  Deberta Input: Which histone marks are deposited by Set7? Set7 deposits the histone marks H3K4me2 and H3K4me3. -> Which histone marks are deposited by Set7? Set7 is a histone methyltransferase that deposits the activating histone mark H3 lysine 4 trimethylation (H3K4me3) and the repressive histone mark H3 lysine 27 trimethylation (H3K27me3).

3  Deberta Input: Is Turcot syndrome associated with glioblastoma? Yes, Turcot syndrome is a rare genetic disorder that is associated with an increased risk of developing glioblastoma, a type of brain cancer. -> Is Turcot syndrome associated with glioblastoma? Turcot syndrome, a rare genetic disorder caused by mutations in the APC gene, is associated with an increased risk of developing glioblastoma, a type of brain cancer.

4  Deberta Input: Which drug can be reversed with idarucizumab? Idarucizumab can reverse the anticoagulant effect of dabigatran. -> Which drug can be reversed with idarucizumab? Dabigatran, an oral direct thrombin inhibitor, can be reversed with idarucizumab.

5  Deberta Input: Is vorinostat effective for glioblastoma? Vorinostat has shown some promise in clinical trials as a potential treatment for glioblastoma, but its overall efficacy remains uncertain due to limited data and the need for further research. -> Is vorinostat effective for glioblastoma? Vorinostat, a histone deacetylase inhibitor, has shown some efficacy in treating glioblastoma, particularly when used in combination with other therapies, although its overall effectiveness is still being studied and refined in clinical trials.

6  Deberta Input: List symptoms of congenital toxoplasmosis triad. The congenital toxoplasmosis triad consists of symptoms such as fever, lymphadenopathy, and hepatosplenomegaly. -> List symptoms of congenital toxoplasmosis triad. Congenital toxoplasmosis triad is characterized by a combination of symptoms including fever, headache, and lymphadenopathy.

7  Deberta Input: Is there a genetic cause of craniostenosis? Yes, craniostenosis can be caused by genetic mutations or variations that affect the development of the skull and facial bones. -> Is there a genetic cause of craniostenosis? Yes, craniostenosis can be caused by genetic mutations that affect the development of the skull and facial bones.

8  Deberta Input: Does oculocutaneous albinism show an autosomal recessive inheritance? Oculocutaneous albinism can show an autosomal recessive inheritance, as mutations in several genes that code for enzymes involved in melanin synthesis can lead to the development of this condition when an individual inherits two copies of the mutated gene, one from each parent. -> Does oculocutaneous albinism show an autosomal recessive inheritance? Yes, oculocutaneous albinism (OCA) typically shows an autosomal recessive inheritance pattern, meaning that an individual must inherit two copies of the mutated gene (one from each parent) to express the condition.

9  Deberta Input: What is the aim of the MitoCeption protocol? The aim of the MitoCeption protocol is to improve mitochondrial function and overall cellular health by activating cellular pathways that promote mitochondrial biogenesis, increasing the number and function of mitochondria, and reducing oxidative stress and inflammation. -> What is the aim of the MitoCeption protocol? The aim of the MitoCeption protocol is to improve mitochondrial function and overall cellular health by enhancing the delivery of essential nutrients and reducing oxidative stress, inflammation, and cellular damage.

10  Deberta Input: List the classical symptoms of the Moschcowitz syndrome (Thrombotic thrombocytopenic purpura). The classical symptoms of Moschcowitz syndrome (Thrombotic thrombocytopenic purpura) include sudden onset of fever, headache, confusion, thrombocytopenia, microangiopathic hemolytic anemia, and neurological symptoms such as seizures, confusion, and coma. -> List the classical symptoms of the Moschcowitz syndrome (Thrombotic thrombocytopenic purpura). The classical symptoms of Moschcowitz syndrome (Thrombotic thrombocytopenic purpura) include confusion, fever, headache, neck pain, vomiting, diarrhea, abdominal pain, dark urine, and petechiae or purpura on the skin.

11  Deberta Input: What is a popular mesaure of gene expression in RNA-seq experiments? A popular measure of gene expression in RNA-seq experiments is the RNA-seq by read count (RSEM) which is a widely used method for estimating gene expression levels from RNA-seq data. -> What is a popular mesaure of gene expression in RNA-seq experiments? A popular measure of gene expression in RNA-seq experiments is RPKM (reads per kilobase of exon model per million reads), which normalizes read counts by library size and gene length to estimate the relative abundance of transcripts.

12  Deberta Input: Is Lysine-specific demethylase 1 (LSD1) a critical regulator of hematopoiesis? LSD1 is a critical regulator of hematopoiesis, as it is required for the maintenance of hematopoietic stem cells and their self-renewal, and its loss leads to impaired hematopoiesis and the development of blood disorders. -> Is Lysine-specific demethylase 1 (LSD1) a critical regulator of hematopoiesis? LSD1 is a critical regulator of hematopoiesis, as it plays a crucial role in the regulation of gene expression and differentiation of hematopoietic stem cells.

13  Deberta Input: What happens to retrotransposons during ageing? Retrotransposons become more active during ageing due to a decline in the mechanisms that normally regulate their expression, leading to increased transcription and insertional mutagenesis, which can contribute to the accumulation of cellular damage and the onset of age-related diseases. -> What happens to retrotransposons during ageing? Retrotransposons, which are remnants of ancient viral infections integrated into the host genome, can become reactivated during ageing and promote cellular senescence and tissue dysfunction through the release of pro-inflammatory cytokines and other factors, contributing to the chronic, low-grade inflammation that characterizes many age-related diseases.

14  Deberta Input: Is the yeast Μac1 transcription factor induced upon copper deficiency? Yes, the yeast Mac1 transcription factor is induced upon copper deficiency as a result of the activation of the copper-responsive regulatory element (CRE) in its promoter region. -> Is the yeast Μac1 transcription factor induced upon copper deficiency? Yes, the yeast Μac1 transcription factor is induced upon copper deficiency as a response to the activation of the Cu-responsive regulatory element (CRE) in its promoter region.

15  Deberta Input: Which drugs are included in the Lonsurf pill? Lonsurf is a fixed-dose combination of two drugs: 5-fluorouracil (5-FU) and folinic acid (leucovorin). -> Which drugs are included in the Lonsurf pill? Lonsurf is a fixed-dose combination of two drugs: 20 mg of bendamustine hydrochloride and 100 mg of trifluridine and tipiracil hydrochloride.

16  Deberta Input: What are the effects of ILK ablation? ILK ablation results in decreased cell adhesion and increased cell migration, suggesting a role for ILK in regulating cellular responses to the extracellular matrix. -> What are the effects of ILK ablation? ILK ablation has been shown to regulate cell adhesion, migration, and survival, and also has a role in cancer progression and cardiovascular disease.

17  Deberta Input: Is YKL-40 used as a biomarker for Alzheimer's disease? YKL-40 is being investigated as a potential biomarker for Alzheimer's disease, but it is not yet widely accepted as a definitive diagnostic marker. -> Is YKL-40 used as a biomarker for Alzheimer's disease? YKL-40 is being investigated as a potential biomarker for Alzheimer's disease, but its accuracy and reliability as a diagnostic tool are still being studied.

18  Deberta Input: Which compounds exist that are thyroid hormone analogs? Thyroid hormone analogs include synthetic compounds such as levothyroxine (T4) and liothyronine (T3), as well as natural compounds found in some plants, such as bugleweed (Lycopus europaeus), motherwort (Leonurus cardiaca), and ashwagandha (Withania somnifera). -> Which compounds exist that are thyroid hormone analogs? Thyroid hormone analogs include synthetic compounds such as levothyroxine (T4) and liothyronine (T3), as well as natural analogs like triiodothyronine (T3) and thyroxine (T4) produced by the thyroid gland.

19  Deberta Input: Where is the body would the Peyer's patches be found The Peyer's patches are found in the small intestine. -> Where is the body would the Peyer's patches be found The Peyer's patches are found in the small intestine.

20  Deberta Input: List genes associated with hypolipidemia. Hypolipidemia has been associated with mutations in genes encoding for proteins involved in lipid metabolism, such as apolipoproteins (APOA1, APOA2, APOC3), lipoprotein receptors (LRP1B, LDLR), enzymes (PCSK9, LIPC2), and transcription factors (SREBP2, PPARG). -> List genes associated with hypolipidemia. Genes associated with hypolipidemia include LDLR, LRP1B, APOE, LMF1, PCSK9, and NPC1L1.

21  Deberta Input: Is palbociclib effective for glioblastoma? Palbociclib has shown some evidence of effectiveness in treating glioblastoma, with studies suggesting that it may slow the growth of tumors and improve overall survival, although further research is needed to confirm these findings and establish its place in the treatment hierarchy for this disease. -> Is palbociclib effective for glioblastoma? Palbociclib, a CDK4/6 inhibitor, has shown some efficacy in treating glioblastoma, particularly when combined with other therapies such as temozolomide, but its overall effectiveness is still limited and more research is needed to determine its long-term benefits and optimal usage in this context.

22  Deberta Input: Is Solanezumab effective for Alzheimer's Disease? Solanezumab has not been shown to be effective for Alzheimer's disease in clinical trials. -> Is Solanezumab effective for Alzheimer's Disease? Solanezumab has not shown significant clinical benefit for patients with mild Alzheimer's disease.

23  Deberta Input: Which disease is treated with Emapalumab? Emapalumab is used to treat primary hemophagocytic lymphohistiocytosis (pHLH), a rare genetic disorder that affects the immune system. -> Which disease is treated with Emapalumab? Emapalumab is used to treat primary hemophagocytic lymphohistiocytosis (HLH).

24  Deberta Input: Which assays can be used for detecting DNA fragmentation resulting from programmed cell death (apoptosis)? Assays that can be used for detecting DNA fragmentation resulting from programmed cell death (apoptosis) include DNA laddering, terminal deoxynucleotidyl transferase (TdT) dUTP nick end labeling (TUNEL) assay, and single-strand conformation polymorphism (SSCP) analysis. -> Which assays can be used for detecting DNA fragmentation resulting from programmed cell death (apoptosis)? Various assays can be used to detect DNA fragmentation resulting from programmed cell death (apoptosis), such as the TUNEL assay, the comet assay, and the DNA ladder assay.

25  Deberta Input: Is Calcium homeostasis important in cardiac physiology and pathophysiology? Calcium homeostasis plays a critical role in cardiac physiology and pathophysiology, as it regulates the contraction and relaxation of the heart muscle, and any disruptions in calcium homeostasis can lead to various cardiac arrhythmias and diseases, such as atrial fibrillation, heart failure, and sudden cardiac death. -> Is Calcium homeostasis important in cardiac physiology and pathophysiology? Calcium homeostasis is critical in cardiac physiology and pathophysiology, as it plays a central role in regulating cardiac muscle contraction and relaxation, and any disruptions in calcium homeostasis can lead to serious cardiac arrhythmias and diseases, such as heart failure and hypertension.

26  Deberta Input: What organism causes woolsorter's disease Woolsorter's disease is caused by the fungus, Microsporum canis. -> What organism causes woolsorter's disease Woolsorter's disease is caused by the fungus, Microsporum canis.

27  Deberta Input: Is the CADM2 gene associated with differences in information processing speed? Yes, genetic variants in the CADM2 gene have been associated with differences in information processing speed, particularly in tasks that require attention and executive functions. -> Is the CADM2 gene associated with differences in information processing speed? Yes, genetic variations in the CADM2 gene have been associated with differences in information processing speed, particularly in tasks that require attention and executive function.

28  Deberta Input: Is Sarcolipin a regulatory/inhibitory protein of the Calcium ATPase SERCA? Sarcolipin is a regulatory protein that inhibits the activity of the Calcium ATPase SERCA by binding to its surface and preventing it from transporting calcium ions across the sarcoplasmic reticulum membrane. -> Is Sarcolipin a regulatory/inhibitory protein of the Calcium ATPase SERCA? Yes, Sarcolipin is a regulatory/inhibitory protein of the Calcium ATPase SERCA.

29  Deberta Input: Which is the RNA sequence of the canonical polyadenylation signal? The canonical polyadenylation signal is the RNA sequence AAUAAA, which is recognized by the cleavage and polyadenylation specific factor (CPSF) and is the most common polyadenylation signal used in eukaryotic mRNAs. -> Which is the RNA sequence of the canonical polyadenylation signal? The RNA sequence of the canonical polyadenylation signal is AATAAA.

30  Deberta Input: List common features of Shapiro syndrome Shapiro syndrome, also known as MEN2A, is characterized by multiple endocrine neoplasia, specifically medullary thyroid carcinoma, pheochromocytoma, and parathyroid gland hyperplasia or adenoma, as well as mucosal and gastrointestinal manifestations such as fibromas, papillomas, and gastric hypertrophic polyps. -> List common features of Shapiro syndrome Shapiro syndrome is a rare genetic disorder characterized by a combination of congenital anomalies, including intellectual disability, seizures, microcephaly, facial dysmorphism, short stature, and limb abnormalities.

31  Deberta Input: Which syndrome is associated with mutations in the LYST gene? Chediak-Higashi syndrome is associated with mutations in the LYST gene. -> Which syndrome is associated with mutations in the LYST gene? Chediak-Higashi syndrome is associated with mutations in the LYST gene.

32  Deberta Input: What 2 biological processes are regulated by STAMP2 in adipocytes? STAMP2 regulates lipolysis and glucose uptake in adipocytes. -> What 2 biological processes are regulated by STAMP2 in adipocytes? STAMP2 regulates lipolysis and glucose uptake in adipocytes.

33  Deberta Input: From which cell type is leptin secreted? Leptin is secreted from adipose tissue, specifically from white adipose tissue. -> From which cell type is leptin secreted? Leptin is secreted from adipocytes, which are specialized fat cells found in white adipose tissue.

34  Deberta Input: Which 2 medications are included in the Qsymia pill? Qsymia contains a combination of phentermine and topiramate. -> Which 2 medications are included in the Qsymia pill? Qsymia contains a combination of phentermine and topiramate.

35  Deberta Input: Which enzyme is deficient in Krabbe disease? Krabbe disease is caused by a deficiency of the enzyme galactocerebrosidase. -> Which enzyme is deficient in Krabbe disease? The enzyme that is deficient in Krabbe disease is galactocerebrosidase.

36  Deberta Input: Is there any role of the 'Greek islands' in olfactory receptor choice? Yes, the Greek islands have a role in olfactory receptor choice, as studies have shown that individuals from certain islands have a higher frequency of specific olfactory receptor genes, which may influence their perception of smells. -> Is there any role of the 'Greek islands' in olfactory receptor choice? The Greek islands have no known role in olfactory receptor choice.

37  Deberta Input: Which X chromosome abnormalities present lupus-like symptoms? Turner syndrome and X-linked lupus can present with lupus-like symptoms. -> Which X chromosome abnormalities present lupus-like symptoms? X chromosome abnormalities that present lupus-like symptoms include Turner syndrome (45,X) and X-linked lupus.

38  Deberta Input: How does the Cholera toxin enter a cell? The Cholera toxin enters a cell through a process called receptor-mediated endocytosis, in which the toxin binds to the GM1 ganglioside receptor on the cell surface and is internalized through a series of vesicle-mediated processes, ultimately resulting in the toxin's delivery to the cytosol. -> How does the Cholera toxin enter a cell? The Cholera toxin enters a cell through a process called receptor-mediated endocytosis, in which the toxin binds to the GM1 ganglioside receptor on the cell surface and is internalized through a series of membrane-bound compartments, ultimately reaching the endoplasmic reticulum where it can interact with its intracellular target, the ADP-ribosylation factor (ARF) protein.

39  Deberta Input: Is inositol effective for trichotillomania? Inositol has been shown to be effective in reducing symptoms of trichotillomania in some studies, but more research is needed to confirm its efficacy and establish its place in the treatment of this condition. -> Is inositol effective for trichotillomania? Inositol may be effective for trichotillomania, as studies have shown that it can help reduce symptoms of compulsive hair pulling in some individuals.

40  Deberta Input: Which MAP kinase phosphorylates the transcription factor c-jun? The MAP kinase ERK phosphorylates the transcription factor c-jun. -> Which MAP kinase phosphorylates the transcription factor c-jun? MAP kinase ERK (Extracellular Signal-Regulated Kinase) phosphorylates the transcription factor c-jun.


# Extract Entailment for existing runs from logs

In [354]:
runs = {
    # '8ehbkd99': 'squad-gpt-4',
    # '5bqecpaq': 'squad-gpt-3.5',
    # 'eriayh79': 'squad-llama-2-70b-chat',
    # '1r6kekju': 'squad-deberta',

    '37it7nr9': 'trivia_qa-gpt-4',
    'mpgj9mz3': 'trivia_qa-gpt-3.5',
    'qfwl6vze': 'trivia_qa-llama-2-70b-chat',
    'f8yk94fy': 'trivia_qa-deberta',
    
    # '3d6obogq': 'bioasq-gpt4',
    # 'jj5da8bd': 'bioasq-gpt3.5',
    # 'lzlhybwt': 'bioasq-deberta',
    # '8i0520i0': 'bioasq-llama-2-70b-chat',
}

In [ ]:
{v: get_slurmid(k) for k, v in runs.items()}

In [332]:
configs = {}
for wandb_id in runs:
    configs[wandb_id] = restore_file(wandb_id, filenames=['config.yaml'])[0]
    
check_first_item(configs)

37it7nr9 167218 trivia_qa  Nigel Hawthorne was Oscar nominated for The Madness of which King?
mpgj9mz3 168315 trivia_qa  Nigel Hawthorne was Oscar nominated for The Madness of which King?
qfwl6vze 171336 trivia_qa  Nigel Hawthorne was Oscar nominated for The Madness of which King?
f8yk94fy 171337 trivia_qa  Nigel Hawthorne was Oscar nominated for The Madness of which King?

In [336]:
get_slurmid = lambda wandbid: api.run(f'goatml/semantic_uncertainty/{wandbid}').notes.split(': ')[1]

In [365]:
# First check runs individually! Then check if they match up!
# Individually: check all 100 inputs make sense!

# CHECKING: does first item line up?
# SKIP_UNTIL = 0
# MAX_NO = 1
# verbose = True

# SKIP_UNTIL = 0
# MAX_NO = 10
# verbose = True

# SKIP_UNTIL = 3
# MAX_NO = 4
# verbose = True

# SKIP_UNTIL = 99
# MAX_NO = 100
# verbose = True


# CHECKING: do things continue to line up at the very end?
# MAX_NO = 99
# SKIP_UNTIL = 98
# verbose = True

MAX_NO = 100
SKIP_UNTIL = 0
verbose = False

# verbose = False


def get_pred(line):
    if 'neutral' in line:
        return 1
    elif 'entailment' in line:
        return 2
    elif 'contradiction' in line:
        return 0
    elif 'prediction: 0' in line:
        return 0
    elif 'prediction: 1' in line:
        return 1
    elif 'prediction: 2' in line:
        return 2
    else:
        raise

preds = {}
for wandbid, name in runs.items():
    # if wandbid != 'f8yk94fy':
        # continue
    
    print(20 * 'xxx')
    print(wandbid, name)

    model = '-'.join(name.split('-')[1:])
    slurmid = get_slurmid(wandbid)
    last_question = ''
    entailment_counter = 0
    entailment_preds = {}
    skip = False
    hit = False
    with open(f'../../log/slurm-{slurmid}.out', 'r') as f:
        lines = f.readlines()
        for i, line in enumerate(lines):
            line = line.lower()

            if 'info' in line:
                line = line[line.index('info'):]

            if f'{model} input:' in line:
                original_line = line

                if model == 'deberta':
                    if 'weight room' in line:
                        line = 'How many weight rooms are in the Malkin Athletic Center'
                    elif '?' in line:
                        line = line[:line.index('?')]
                    elif '.' in line[:50]:
                        line = line[:line.index('.')]
                    else:
                        line = line[:40]
                
                if line == last_question:
                    skip = True
                    hit = False
                    continue
                else:
                    skip = False

                last_question = line
                if verbose and (entailment_counter >= SKIP_UNTIL):
                    print('----')
                    if model == 'deberta':
                        print(i, 'INPT', original_line)
                    else:
                        print(i, 'INPT', line)
                        print(i+2, 'INPT', lines[i+2])
                        print(i+3, 'INPT', lines[i+3])
                entailment_counter += 1

            if not skip and (f'{model} prediction:' in line):
                hit = True
                entailment_prediction = get_pred(line)
                if verbose and (entailment_counter > SKIP_UNTIL):
                    print(i, 'ANSWER', line)
                    print(i, 'ANSWER', entailment_prediction)
                entailment_preds[entailment_counter] = entailment_prediction
            
            sys.stdout.flush()
            if (entailment_counter == MAX_NO) and hit:
                break
    preds[wandbid] = entailment_preds

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
37it7nr9 trivia_qa-gpt-4
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mpgj9mz3 trivia_qa-gpt-3.5
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
qfwl6vze trivia_qa-llama-2-70b-chat
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
f8yk94fy trivia_qa-deberta

In [367]:
df = pd.DataFrame.from_dict(preds).rename(columns=lambda x: runs[x])
# for rater in ['squad-human_jansen', 'squad-human_sebhar']:
for rater in [f'{k}-human_jansen' for k in ['trivia_qa', 'bioasq']]:
    df[rater] = 'FILL_IN'
df

,trivia_qa-gpt-4,trivia_qa-gpt-3.5,trivia_qa-llama-2-70b-chat,trivia_qa-deberta,trivia_qa-human_jansen,bioasq-human_jansen
1,2,2,2,1,FILL_IN,FILL_IN
2,2,2,2,2,FILL_IN,FILL_IN
3,2,2,2,2,FILL_IN,FILL_IN
4,2,2,2,1,FILL_IN,FILL_IN
5,2,2,2,2,FILL_IN,FILL_IN
...,...,...,...,...,...,...
96,2,2,2,2,FILL_IN,FILL_IN
97,2,2,2,2,FILL_IN,FILL_IN
98,2,2,2,2,FILL_IN,FILL_IN
99,2,2,2,2,FILL_IN,FILL_IN
100,2,2,2,2,FILL_IN,FILL_IN

In [368]:
tmp = df.reset_index().melt(id_vars='index', value_vars=df.columns)
tmp['dataset'] = tmp.variable.map(lambda x: x.split('-')[0])
tmp['model'] = tmp.variable.map(lambda x: '-'.join(x.split('-')[1:]))
tmp = tmp[['index', 'dataset', 'model', 'value']]
tmp['index'] = tmp['index'] - 1
tmp
# tmp.to_csv('23-11-24-entailment-evaluation.csv', index=False)

     index    dataset         model    value
0        0  trivia_qa         gpt-4        2
1        1  trivia_qa         gpt-4        2
2        2  trivia_qa         gpt-4        2
3        3  trivia_qa         gpt-4        2
4        4  trivia_qa         gpt-4        2
..     ...        ...           ...      ...
595     95     bioasq  human_jansen  FILL_IN
596     96     bioasq  human_jansen  FILL_IN
597     97     bioasq  human_jansen  FILL_IN
598     98     bioasq  human_jansen  FILL_IN
599     99     bioasq  human_jansen  FILL_IN

[600 rows x 4 columns]

In [370]:
print(tmp.to_csv())

,index,dataset,model,value
0,0,trivia_qa,gpt-4,2
1,1,trivia_qa,gpt-4,2
2,2,trivia_qa,gpt-4,2
3,3,trivia_qa,gpt-4,2
4,4,trivia_qa,gpt-4,2
5,5,trivia_qa,gpt-4,2
6,6,trivia_qa,gpt-4,2
7,7,trivia_qa,gpt-4,2
8,8,trivia_qa,gpt-4,2
9,9,trivia_qa,gpt-4,2
10,10,trivia_qa,gpt-4,2
11,11,trivia_qa,gpt-4,2
12,12,trivia_qa,gpt-4,0
13,13,trivia_qa,gpt-4,2
14,14,trivia_qa,gpt-4,2
15,15,trivia_qa,gpt-4,2
16,16,trivia_qa,gpt-4,1
17,17,trivia_qa,gpt-4,2
18,18,trivia_qa,gpt-4,2
19,19,trivia_qa,gpt-4,2
20,20,trivia_qa,gpt-4,2
21,21,trivia_qa,gpt-4,2
22,22,trivia_qa,gpt-4,0
23,23,trivia_qa,gpt-4,2
24,24,trivia_qa,gpt-4,2
25,25,trivia_qa,gpt-4,2
26,26,trivia_qa,gpt-4,2
27,27,trivia_qa,gpt-4,2
28,28,trivia_qa,gpt-4,2
29,29,trivia_qa,gpt-4,1
30,30,trivia_qa,gpt-4,2
31,31,trivia_qa,gpt-4,2
32,32,trivia_qa,gpt-4,2
33,33,trivia_qa,gpt-4,2
34,34,trivia_qa,gpt-4,0
35,35,trivia_qa,gpt-4,2
36,36,trivia_qa,gpt-4,2
37,37,trivia_qa,gpt-4,2
38,38,trivia_qa,gpt-4,2
39,39,trivia_qa,gpt-4,2
40,40,trivia_qa,gpt-4,0
41,41,trivia_qa,gpt-4,2
42,42,trivia_qa,gpt-4,1
43,43,trivia_qa,gpt-4,2
44,44,trivia_qa,gpt-4,2
45,45,trivia_qa,gpt-4,2
46,46,trivia_qa,gpt-4,2
47,47,trivia_qa,gpt-4,2
48,48,trivia_qa,gpt-4,2
49,49,trivia_qa,gpt-4,2
50,50,trivia_qa,gpt-4,2
51,51,trivia_qa,gpt-4,1
52,52,trivia_qa,gpt-4,2
53,53,trivia_qa,gpt-4,1
54,54,trivia_qa,gpt-4,2
55,55,trivia_qa,gpt-4,2
56,56,trivia_qa,gpt-4,2
57,57,trivia_qa,gpt-4,2
58,58,trivia_qa,gpt-4,1
59,59,trivia_qa,gpt-4,2
60,60,trivia_qa,gpt-4,2
61,61,trivia_qa,gpt-4,2
62,62,trivia_qa,gpt-4,2
63,63,trivia_qa,gpt-4,2
64,64,trivia_qa,gpt-4,2
65,65,trivia_qa,gpt-4,2
66,66,trivia_qa,gpt-4,2
67,67,trivia_qa,gpt-4,1
68,68,trivia_qa,gpt-4,2
69,69,trivia_qa,gpt-4,2
70,70,trivia_qa,gpt-4,2
71,71,trivia_qa,gpt-4,2
72,72,trivia_qa,gpt-4,2
73,73,trivia_qa,gpt-4,1
74,74,trivia_qa,gpt-4,2
75,75,trivia_qa,gpt-4,1
76,76,trivia_qa,gpt-4,0
77,77,trivia_qa,gpt-4,2
78,78,trivia_qa,gpt-4,2
79,79,trivia_qa,gpt-4,0
80,80,trivia_qa,gpt-4,2
81,81,trivia_qa,gpt-4,2
82,82,trivia_qa,gpt-4,2
83,83,trivia_qa,gpt-4,2
84,84,trivia_qa,gpt-4,0
85,85,trivia_qa,gpt-4,2
86,86,trivia_qa,gpt-4,2
87,87,trivia_qa,gpt-4,2
88,88,trivia_qa,gpt-4,2
89,89,trivia_qa,gpt-4,2
90,90,trivia_qa,gpt-4,2
91,91,trivia_qa,gpt-4,1
92,92,trivia_qa,gpt-4,2
93,93,trivia_qa,gpt-4,2
94,94,trivia_qa,gpt-4,2
95,95,trivia_qa,gpt-4,2
96,96,trivia_qa,gpt-4,2
97,97,trivia_qa,gpt-4,2
98,98,trivia_qa,gpt-4,2
99,99,trivia_qa,gpt-4,2
100,0,trivia_qa,gpt-3.5,2
101,1,trivia_qa,gpt-3.5,2
102,2,trivia_qa,gpt-3.5,2
103,3,trivia_qa,gpt-3.5,2
104,4,trivia_qa,gpt-3.5,2
105,5,trivia_qa,gpt-3.5,2
106,6,trivia_qa,gpt-3.5,2
107,7,trivia_qa,gpt-3.5,2
108,8,trivia_qa,gpt-3.5,2
109,9,trivia_qa,gpt-3.5,2
110,10,trivia_qa,gpt-3.5,2
111,11,trivia_qa,gpt-3.5,2
112,12,trivia_qa,gpt-3.5,1
113,13,trivia_qa,gpt-3.5,2
114,14,trivia_qa,gpt-3.5,2
115,15,trivia_qa,gpt-3.5,2
116,16,trivia_qa,gpt-3.5,1
117,17,trivia_qa,gpt-3.5,2
118,18,trivia_qa,gpt-3.5,2
119,19,trivia_qa,gpt-3.5,2
120,20,trivia_qa,gpt-3.5,2
121,21,trivia_qa,gpt-3.5,2
122,22,trivia_qa,gpt-3.5,2
123,23,trivia_qa,gpt-3.5,2
124,24,trivia_qa,gpt-3.5,2
125,25,trivia_qa,gpt-3.5,2
126,26,trivia_qa,gpt-3.5,2
127,27,trivia_qa,gpt-3.5,2
128,28,trivia_qa,gpt-3.5,2
129,29,trivia_qa,gpt-3.5,2
130,30,trivia_qa,gpt-3.5,2
131,31,trivia_qa,gpt-3.5,2
132,32,trivia_qa,gpt-3.5,2
133,33,trivia_qa,gpt-3.5,2
134,34,trivia_qa,gpt-3.5,2
135,35,trivia_qa,gpt-3.5,2
136,36,trivia_qa,gpt-3.5,2
137,37,trivia_qa,gpt-3.5,2
138,38,trivia_qa,gpt-3.5,2
139,39,trivia_qa,gpt-3.5,2
140,40,trivia_qa,gpt-3.5,0
141,41,trivia_qa,gpt-3.5,2
142,42,trivia_qa,gpt-3.5,2
143,43,trivia_qa,gpt-3.5,2
144,44,trivia_qa,gpt-3.5,2
145,45,trivia_qa,gpt-3.5,2
146,46,trivia_qa,gpt-3.5,2
147,47,trivia_qa,gpt-3.5,2
148,48,trivia_qa,gpt-3.5,2
149,49,trivia_qa,gpt-3.5,2
150,50,trivia_qa,gpt-3.5,2
151,51,trivia_qa,gpt-3.5,1
152,52,trivia_qa,gpt-3.5,2
153,53,trivia_qa,gpt-3.5,2
154,54,trivia_qa,gpt-3.5,2
155,55,trivia_qa,gpt-3.5,2
156,56,trivia_qa,gpt-3.5,2
157,57,trivia_qa,gpt-3.5,2
158,58,trivia_qa,gpt-3.5,1
159,59,trivia_qa,gpt-3.5,2
160,60,trivia_qa,gpt-3.5,2
161,61,trivia_qa,gpt-3.5,2
162,62,trivia_qa,gpt-3.5,2
163,63,trivia_qa,gpt-3.5,2
164,64,trivia_qa,gpt-3.5,2
165,65,trivia_qa,gpt-3.5,2
166,66,trivia_qa,gpt-3.5,2
167,67,trivia_qa,gpt-3.5,2
168,68,trivia_qa,gpt-3.5,2
169,69,trivia_qa,gpt-3.5,2
170,70,trivia_qa,gpt-3.5,2
171,71,trivia_qa,gpt-3.5,2
172,72,trivia_qa,gpt-3.5,2
173,73,trivia_qa,gpt-3.5,2
174,74,trivia_qa,gpt-3.5,2
175,75,trivia_qa,gpt-3.5,0
176,76,trivia_qa,gpt-3.5,0
177,77,trivia_qa,gpt-3.5,2
178,78,trivia_qa,gpt-3.5,2
179,79,trivia_qa,gpt-3.5,0
180,80,trivia_qa,gpt-3.5,2
181,81,trivia_qa,gpt-3.5,2
182,82,trivia_qa,gpt-3.5,2
183,83,trivia_qa,gpt-3.5,2
184,84,trivia_qa,gpt-3.5,2
185,85,trivia_qa,gpt-3.5,2
186,86,trivia_qa,gpt-3.5,2
187,87,trivia_qa,gpt-3.5,2
188,88,trivia_qa,gpt-3.5,2
189,89,trivia_qa,gpt-3.5,2
190,90,trivia_qa,gpt-3.5,2
191,91,trivia_qa,gpt-3.5,2
192,92,trivia_qa,gpt-3.5,2
193,93,trivia_qa,gpt-3.5,2
194,94,trivia_qa,gpt-3.5,2
195,95,trivia_qa,gpt-3.5,2
196,96,trivia_qa,gpt-3.5,2
197,97,trivia_qa,gpt-3.5,2
198,98,trivia_qa,gpt-3.5,2
199,99,trivia_qa,gpt-3.5,2
200,0,trivia_qa,llama-2-70b-chat,2
201,1,trivia_qa,llama-2-70b-chat,2
202,2,trivia_qa,llama-2-70b-chat,2
203,3,trivia_qa,llama-2-70b-chat,2
204,4,trivia_qa,llama-2-70b-chat,2
205,5,trivia_qa,llama-2-70b-chat,2
206,6,trivia_qa,llama-2-70b-chat,2
207,7,trivia_qa,llama-2-70b-chat,2
208,8,trivia_qa,llama-2-70b-chat,2
209,9,trivia_qa,llama-2-70b-chat,2
210,10,trivia_qa,llama-2-70b-chat,2
211,11,trivia_qa,llama-2-70b-chat,2
212,12,trivia_qa,llama-2-70b-chat,2
213,13,trivia_qa,llama-2-70b-chat,2
214,14,trivia_qa,llama-2-70b-chat,2
215,15,trivia_qa,llama-2-70b-chat,2
216,16,trivia_qa,llama-2-70b-chat,2
217,17,trivia_qa,llama-2-70b-chat,2
218,18,trivia_qa,llama-2-70b-chat,2
219,19,trivia_qa,llama-2-70b-chat,2
220,20,trivia_qa,llama-2-70b-chat,2
221,21,trivia_qa,llama-2-70b-chat,2
222,22,trivia_qa,llama-2-70b-chat,2
223,23,trivia_qa,llama-2-70b-chat,2
224,24,trivia_qa,llama-2-70b-chat,2
225,25,trivia_qa,llama-2-70b-chat,2
226,26,trivia_qa,llama-2-70b-chat,2
227,27,trivia_qa,llama-2-70b-chat,2
228,28,trivia_qa,llama-2-70b-chat,2
229,29,trivia_qa,llama-2-70b-chat,2
230,30,trivia_qa,llama-2-70b-chat,2
231,31,trivia_qa,llama-2-70b-chat,2
232,32,trivia_qa,llama-2-70b-chat,2
233,33,trivia_qa,llama-2-70b-chat,2
234,34,trivia_qa,llama-2-70b-chat,0
235,35,trivia_qa,llama-2-70b-chat,2
236,36,trivia_qa,llama-2-70b-chat,2
237,37,trivia_qa,llama-2-70b-chat,2
238,38,trivia_qa,llama-2-70b-chat,2
239,39,trivia_qa,llama-2-70b-chat,2
240,40,trivia_qa,llama-2-70b-chat,0
241,41,trivia_qa,llama-2-70b-chat,2
242,42,trivia_qa,llama-2-70b-chat,2
243,43,trivia_qa,llama-2-70b-chat,2
244,44,trivia_qa,llama-2-70b-chat,2
245,45,trivia_qa,llama-2-70b-chat,2
246,46,trivia_qa,llama-2-70b-chat,2
247,47,trivia_qa,llama-2-70b-chat,2
248,48,trivia_qa,llama-2-70b-chat,2
249,49,trivia_qa,llama-2-70b-chat,2
250,50,trivia_qa,llama-2-70b-chat,2
251,51,trivia_qa,llama-2-70b-chat,2
252,52,trivia_qa,llama-2-70b-chat,2
253,53,trivia_qa,llama-2-70b-chat,2
254,54,trivia_qa,llama-2-70b-chat,2
255,55,trivia_qa,llama-2-70b-chat,2
256,56,trivia_qa,llama-2-70b-chat,2
257,57,trivia_qa,llama-2-70b-chat,2
258,58,trivia_qa,llama-2-70b-chat,1
259,59,trivia_qa,llama-2-70b-chat,2
260,60,trivia_qa,llama-2-70b-chat,2
261,61,trivia_qa,llama-2-70b-chat,2
262,62,trivia_qa,llama-2-70b-chat,2
263,63,trivia_qa,llama-2-70b-chat,2
264,64,trivia_qa,llama-2-70b-chat,2
265,65,trivia_qa,llama-2-70b-chat,2
266,66,trivia_qa,llama-2-70b-chat,2
267,67,trivia_qa,llama-2-70b-chat,2
268,68,trivia_qa,llama-2-70b-chat,2
269,69,trivia_qa,llama-2-70b-chat,2
270,70,trivia_qa,llama-2-70b-chat,2
271,71,trivia_qa,llama-2-70b-chat,2
272,72,trivia_qa,llama-2-70b-chat,2
273,73,trivia_qa,llama-2-70b-chat,2
274,74,trivia_qa,llama-2-70b-chat,2
275,75,trivia_qa,llama-2-70b-chat,0
276,76,trivia_qa,llama-2-70b-chat,0
277,77,trivia_qa,llama-2-70b-chat,2
278,78,trivia_qa,llama-2-70b-chat,2
279,79,trivia_qa,llama-2-70b-chat,0
280,80,trivia_qa,llama-2-70b-chat,2
281,81,trivia_qa,llama-2-70b-chat,2
282,82,trivia_qa,llama-2-70b-chat,2
283,83,trivia_qa,llama-2-70b-chat,2
284,84,trivia_qa,llama-2-70b-chat,2
285,85,trivia_qa,llama-2-70b-chat,2
286,86,trivia_qa,llama-2-70b-chat,2
287,87,trivia_qa,llama-2-70b-chat,2
288,88,trivia_qa,llama-2-70b-chat,2
289,89,trivia_qa,llama-2-70b-chat,2
290,90,trivia_qa,llama-2-70b-chat,2
291,91,trivia_qa,llama-2-70b-chat,0
292,92,trivia_qa,llama-2-70b-chat,2
293,93,trivia_qa,llama-2-70b-chat,2
294,94,trivia_qa,llama-2-70b-chat,2
295,95,trivia_qa,llama-2-70b-chat,2
296,96,trivia_qa,llama-2-70b-chat,2
297,97,trivia_qa,llama-2-70b-chat,2
298,98,trivia_qa,llama-2-70b-chat,2
299,99,trivia_qa,llama-2-70b-chat,2
300,0,trivia_qa,deberta,1
301,1,trivia_qa,deberta,2
302,2,trivia_qa,deberta,2
303,3,trivia_qa,deberta,1
304,4,trivia_qa,deberta,2
305,5,trivia_qa,deberta,2
306,6,trivia_qa,deberta,1
307,7,trivia_qa,deberta,2
308,8,trivia_qa,deberta,2
309,9,trivia_qa,deberta,2
310,10,trivia_qa,deberta,2
311,11,trivia_qa,deberta,2
312,12,trivia_qa,deberta,2
313,13,trivia_qa,deberta,2
314,14,trivia_qa,deberta,2
315,15,trivia_qa,deberta,2
316,16,trivia_qa,deberta,1
317,17,trivia_qa,deberta,2
318,18,trivia_qa,deberta,2
319,19,trivia_qa,deberta,2
320,20,trivia_qa,deberta,2
321,21,trivia_qa,deberta,2
322,22,trivia_qa,deberta,2
323,23,trivia_qa,deberta,2
324,24,trivia_qa,deberta,2
325,25,trivia_qa,deberta,2
326,26,trivia_qa,deberta,1
327,27,trivia_qa,deberta,2
328,28,trivia_qa,deberta,2
329,29,trivia_qa,deberta,0
330,30,trivia_qa,deberta,2
331,31,trivia_qa,deberta,2
332,32,trivia_qa,deberta,2
333,33,trivia_qa,deberta,2
334,34,trivia_qa,deberta,0
335,35,trivia_qa,deberta,2
336,36,trivia_qa,deberta,2
337,37,trivia_qa,deberta,2
338,38,trivia_qa,deberta,2
339,39,trivia_qa,deberta,2
340,40,trivia_qa,deberta,0
341,41,trivia_qa,deberta,2
342,42,trivia_qa,deberta,1
343,43,trivia_qa,deberta,2
344,44,trivia_qa,deberta,2
345,45,trivia_qa,deberta,2
346,46,trivia_qa,deberta,2
347,47,trivia_qa,deberta,2
348,48,trivia_qa,deberta,2
349,49,trivia_qa,deberta,2
350,50,trivia_qa,deberta,2
351,51,trivia_qa,deberta,1
352,52,trivia_qa,deberta,2
353,53,trivia_qa,deberta,1
354,54,trivia_qa,deberta,2
355,55,trivia_qa,deberta,2
356,56,trivia_qa,deberta,2
357,57,trivia_qa,deberta,2
358,58,trivia_qa,deberta,0
359,59,trivia_qa,deberta,2
360,60,trivia_qa,deberta,2
361,61,trivia_qa,deberta,2
362,62,trivia_qa,deberta,2
363,63,trivia_qa,deberta,2
364,64,trivia_qa,deberta,2
365,65,trivia_qa,deberta,2
366,66,trivia_qa,deberta,2
367,67,trivia_qa,deberta,1
368,68,trivia_qa,deberta,2
369,69,trivia_qa,deberta,2
370,70,trivia_qa,deberta,1
371,71,trivia_qa,deberta,2
372,72,trivia_qa,deberta,2
373,73,trivia_qa,deberta,1
374,74,trivia_qa,deberta,1
375,75,trivia_qa,deberta,0
376,76,trivia_qa,deberta,0
377,77,trivia_qa,deberta,2
378,78,trivia_qa,deberta,2
379,79,trivia_qa,deberta,0
380,80,trivia_qa,deberta,2
381,81,trivia_qa,deberta,2
382,82,trivia_qa,deberta,2
383,83,trivia_qa,deberta,2
384,84,trivia_qa,deberta,0
385,85,trivia_qa,deberta,2
386,86,trivia_qa,deberta,2
387,87,trivia_qa,deberta,2
388,88,trivia_qa,deberta,2
389,89,trivia_qa,deberta,1
390,90,trivia_qa,deberta,2
391,91,trivia_qa,deberta,0
392,92,trivia_qa,deberta,2
393,93,trivia_qa,deberta,2
394,94,trivia_qa,deberta,2
395,95,trivia_qa,deberta,2
396,96,trivia_qa,deberta,2
397,97,trivia_qa,deberta,2
398,98,trivia_qa,deberta,2
399,99,trivia_qa,deberta,2
400,0,trivia_qa,human_jansen,FILL_IN
401,1,trivia_qa,human_jansen,FILL_IN
402,2,trivia_qa,human_jansen,FILL_IN
403,3,trivia_qa,human_jansen,FILL_IN
404,4,trivia_qa,human_jansen,FILL_IN
405,5,trivia_qa,human_jansen,FILL_IN
406,6,trivia_qa,human_jansen,FILL_IN
407,7,trivia_qa,human_jansen,FILL_IN
408,8,trivia_qa,human_jansen,FILL_IN
409,9,trivia_qa,human_jansen,FILL_IN
410,10,trivia_qa,human_jansen,FILL_IN
411,11,trivia_qa,human_jansen,FILL_IN
412,12,trivia_qa,human_jansen,FILL_IN
413,13,trivia_qa,human_jansen,FILL_IN
414,14,trivia_qa,human_jansen,FILL_IN
415,15,trivia_qa,human_jansen,FILL_IN
416,16,trivia_qa,human_jansen,FILL_IN
417,17,trivia_qa,human_jansen,FILL_IN
418,18,trivia_qa,human_jansen,FILL_IN
419,19,trivia_qa,human_jansen,FILL_IN
420,20,trivia_qa,human_jansen,FILL_IN
421,21,trivia_qa,human_jansen,FILL_IN
422,22,trivia_qa,human_jansen,FILL_IN
423,23,trivia_qa,human_jansen,FILL_IN
424,24,trivia_qa,human_jansen,FILL_IN
425,25,trivia_qa,human_jansen,FILL_IN
426,26,trivia_qa,human_jansen,FILL_IN
427,27,trivia_qa,human_jansen,FILL_IN
428,28,trivia_qa,human_jansen,FILL_IN
429,29,trivia_qa,human_jansen,FILL_IN
430,30,trivia_qa,human_jansen,FILL_IN
431,31,trivia_qa,human_jansen,FILL_IN
432,32,trivia_qa,human_jansen,FILL_IN
433,33,trivia_qa,human_jansen,FILL_IN
434,34,trivia_qa,human_jansen,FILL_IN
435,35,trivia_qa,human_jansen,FILL_IN
436,36,trivia_qa,human_jansen,FILL_IN
437,37,trivia_qa,human_jansen,FILL_IN
438,38,trivia_qa,human_jansen,FILL_IN
439,39,trivia_qa,human_jansen,FILL_IN
440,40,trivia_qa,human_jansen,FILL_IN
441,41,trivia_qa,human_jansen,FILL_IN
442,42,trivia_qa,human_jansen,FILL_IN
443,43,trivia_qa,human_jansen,FILL_IN
444,44,trivia_qa,human_jansen,FILL_IN
445,45,trivia_qa,human_jansen,FILL_IN
446,46,trivia_qa,human_jansen,FILL_IN
447,47,trivia_qa,human_jansen,FILL_IN
448,48,trivia_qa,human_jansen,FILL_IN
449,49,trivia_qa,human_jansen,FILL_IN
450,50,trivia_qa,human_jansen,FILL_IN
451,51,trivia_qa,human_jansen,FILL_IN
452,52,trivia_qa,human_jansen,FILL_IN
453,53,trivia_qa,human_jansen,FILL_IN
454,54,trivia_qa,human_jansen,FILL_IN
455,55,trivia_qa,human_jansen,FILL_IN
456,56,trivia_qa,human_jansen,FILL_IN
457,57,trivia_qa,human_jansen,FILL_IN
458,58,trivia_qa,human_jansen,FILL_IN
459,59,trivia_qa,human_jansen,FILL_IN
460,60,trivia_qa,human_jansen,FILL_IN
461,61,trivia_qa,human_jansen,FILL_IN
462,62,trivia_qa,human_jansen,FILL_IN
463,63,trivia_qa,human_jansen,FILL_IN
464,64,trivia_qa,human_jansen,FILL_IN
465,65,trivia_qa,human_jansen,FILL_IN
466,66,trivia_qa,human_jansen,FILL_IN
467,67,trivia_qa,human_jansen,FILL_IN
468,68,trivia_qa,human_jansen,FILL_IN
469,69,trivia_qa,human_jansen,FILL_IN
470,70,trivia_qa,human_jansen,FILL_IN
471,71,trivia_qa,human_jansen,FILL_IN
472,72,trivia_qa,human_jansen,FILL_IN
473,73,trivia_qa,human_jansen,FILL_IN
474,74,trivia_qa,human_jansen,FILL_IN
475,75,trivia_qa,human_jansen,FILL_IN
476,76,trivia_qa,human_jansen,FILL_IN
477,77,trivia_qa,human_jansen,FILL_IN
478,78,trivia_qa,human_jansen,FILL_IN
479,79,trivia_qa,human_jansen,FILL_IN
480,80,trivia_qa,human_jansen,FILL_IN
481,81,trivia_qa,human_jansen,FILL_IN
482,82,trivia_qa,human_jansen,FILL_IN
483,83,trivia_qa,human_jansen,FILL_IN
484,84,trivia_qa,human_jansen,FILL_IN
485,85,trivia_qa,human_jansen,FILL_IN
486,86,trivia_qa,human_jansen,FILL_IN
487,87,trivia_qa,human_jansen,FILL_IN
488,88,trivia_qa,human_jansen,FILL_IN
489,89,trivia_qa,human_jansen,FILL_IN
490,90,trivia_qa,human_jansen,FILL_IN
491,91,trivia_qa,human_jansen,FILL_IN
492,92,trivia_qa,human_jansen,FILL_IN
493,93,trivia_qa,human_jansen,FILL_IN
494,94,trivia_qa,human_jansen,FILL_IN
495,95,trivia_qa,human_jansen,FILL_IN
496,96,trivia_qa,human_jansen,FILL_IN
497,97,trivia_qa,human_jansen,FILL_IN
498,98,trivia_qa,human_jansen,FILL_IN
499,99,trivia_qa,human_jansen,FILL_IN
500,0,bioasq,human_jansen,FILL_IN
501,1,bioasq,human_jansen,FILL_IN
502,2,bioasq,human_jansen,FILL_IN
503,3,bioasq,human_jansen,FILL_IN
504,4,bioasq,human_jansen,FILL_IN
505,5,bioasq,human_jansen,FILL_IN
506,6,bioasq,human_jansen,FILL_IN
507,7,bioasq,human_jansen,FILL_IN
508,8,bioasq,human_jansen,FILL_IN
509,9,bioasq,human_jansen,FILL_IN
510,10,bioasq,human_jansen,FILL_IN
511,11,bioasq,human_jansen,FILL_IN
512,12,bioasq,human_jansen,FILL_IN
513,13,bioasq,human_jansen,FILL_IN
514,14,bioasq,human_jansen,FILL_IN
515,15,bioasq,human_jansen,FILL_IN
516,16,bioasq,human_jansen,FILL_IN
517,17,bioasq,human_jansen,FILL_IN
518,18,bioasq,human_jansen,FILL_IN
519,19,bioasq,human_jansen,FILL_IN
520,20,bioasq,human_jansen,FILL_IN
521,21,bioasq,human_jansen,FILL_IN
522,22,bioasq,human_jansen,FILL_IN
523,23,bioasq,human_jansen,FILL_IN
524,24,bioasq,human_jansen,FILL_IN
525,25,bioasq,human_jansen,FILL_IN
526,26,bioasq,human_jansen,FILL_IN
527,27,bioasq,human_jansen,FILL_IN
528,28,bioasq,human_jansen,FILL_IN
529,29,bioasq,human_jansen,FILL_IN
530,30,bioasq,human_jansen,FILL_IN
531,31,bioasq,human_jansen,FILL_IN
532,32,bioasq,human_jansen,FILL_IN
533,33,bioasq,human_jansen,FILL_IN
534,34,bioasq,human_jansen,FILL_IN
535,35,bioasq,human_jansen,FILL_IN
536,36,bioasq,human_jansen,FILL_IN
537,37,bioasq,human_jansen,FILL_IN
538,38,bioasq,human_jansen,FILL_IN
539,39,bioasq,human_jansen,FILL_IN
540,40,bioasq,human_jansen,FILL_IN
541,41,bioasq,human_jansen,FILL_IN
542,42,bioasq,human_jansen,FILL_IN
543,43,bioasq,human_jansen,FILL_IN
544,44,bioasq,human_jansen,FILL_IN
545,45,bioasq,human_jansen,FILL_IN
546,46,bioasq,human_jansen,FILL_IN
547,47,bioasq,human_jansen,FILL_IN
548,48,bioasq,human_jansen,FILL_IN
549,49,bioasq,human_jansen,FILL_IN
550,50,bioasq,human_jansen,FILL_IN
551,51,bioasq,human_jansen,FILL_IN
552,52,bioasq,human_jansen,FILL_IN
553,53,bioasq,human_jansen,FILL_IN
554,54,bioasq,human_jansen,FILL_IN
555,55,bioasq,human_jansen,FILL_IN
556,56,bioasq,human_jansen,FILL_IN
557,57,bioasq,human_jansen,FILL_IN
558,58,bioasq,human_jansen,FILL_IN
559,59,bioasq,human_jansen,FILL_IN
560,60,bioasq,human_jansen,FILL_IN
561,61,bioasq,human_jansen,FILL_IN
562,62,bioasq,human_jansen,FILL_IN
563,63,bioasq,human_jansen,FILL_IN
564,64,bioasq,human_jansen,FILL_IN
565,65,bioasq,human_jansen,FILL_IN
566,66,bioasq,human_jansen,FILL_IN
567,67,bioasq,human_jansen,FILL_IN
568,68,bioasq,human_jansen,FILL_IN
569,69,bioasq,human_jansen,FILL_IN
570,70,bioasq,human_jansen,FILL_IN
571,71,bioasq,human_jansen,FILL_IN
572,72,bioasq,human_jansen,FILL_IN
573,73,bioasq,human_jansen,FILL_IN
574,74,bioasq,human_jansen,FILL_IN
575,75,bioasq,human_jansen,FILL_IN
576,76,bioasq,human_jansen,FILL_IN
577,77,bioasq,human_jansen,FILL_IN
578,78,bioasq,human_jansen,FILL_IN
579,79,bioasq,human_jansen,FILL_IN
580,80,bioasq,human_jansen,FILL_IN
581,81,bioasq,human_jansen,FILL_IN
582,82,bioasq,human_jansen,FILL_IN
583,83,bioasq,human_jansen,FILL_IN
584,84,bioasq,human_jansen,FILL_IN
585,85,bioasq,human_jansen,FILL_IN
586,86,bioasq,human_jansen,FILL_IN
587,87,bioasq,human_jansen,FILL_IN
588,88,bioasq,human_jansen,FILL_IN
589,89,bioasq,human_jansen,FILL_IN
590,90,bioasq,human_jansen,FILL_IN
591,91,bioasq,human_jansen,FILL_IN
592,92,bioasq,human_jansen,FILL_IN
593,93,bioasq,human_jansen,FILL_IN
594,94,bioasq,human_jansen,FILL_IN
595,95,bioasq,human_jansen,FILL_IN
596,96,bioasq,human_jansen,FILL_IN
597,97,bioasq,human_jansen,FILL_IN
598,98,bioasq,human_jansen,FILL_IN
599,99,bioasq,human_jansen,FILL_IN

In [291]:
tmp.model.unique()

array(['gpt-4', 'gpt-3.5', 'llama-2-70b-chat', 'deberta'], dtype=object)

In [289]:
tmp[tmp.model == 'sebhar']

Empty DataFrame
Columns: [index, dataset, model, value]
Index: []

# Analysis: Correlation between entailment metrics and human judgement

In [316]:
df = pd.read_csv('23-11-28-entailment-evaluation.csv', index_col=None)

In [317]:
def remove_incomplete(df):
    # filter out incomplete data!
    ignore = []
    for metric, mdf in df.groupby('model'):
        if (mdf.value == 'FILL_IN').any():
            ignore.append(metric)
    print(f'Ignoring metrics {ignore} for now.')
    df = df[df.model.map(lambda x: x not in ignore)]
    return df

df = remove_incomplete(df)

Ignoring metrics [] for now.

In [318]:
for name, tmp in df.groupby(['index', 'dataset', 'model']):
    if len(tmp) > 1:
        print(name)
        display(tmp)

In [328]:
def agreement(x, y):
    return np.mean(x == y)


for method in ['pearson', 'kendall', 'spearman', agreement, cohen_kappa_score]:
    print(90*'x')
    print(colorize(f'METHOD: {method}'))
    print(90*'x')

    for dataset, gdf in df.groupby('dataset'):
        pdf = gdf.pivot(index='index', columns='model', values='value')    
        print(colorize(f'method: {method} -- dataset: {dataset}', 1))
        display(pdf.corr(method=method))

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
METHOD: pearson
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
method: pearson -- dataset: bioasq

model         human_sebhar
model
human_sebhar           1.0

method: pearson -- dataset: squad

model,deberta,gpt-3.5,gpt-4,human_jansen,human_sebhar,llama-2-70b-chat
model,,,,,,
deberta,1.000000,0.694685,0.730558,0.620574,0.633727,0.512429
gpt-3.5,0.694685,1.000000,0.740407,0.690731,0.650650,0.528964
gpt-4,0.730558,0.740407,1.000000,0.748663,0.616427,0.447512
human_jansen,0.620574,0.690731,0.748663,1.000000,0.675886,0.462562
human_sebhar,0.633727,0.650650,0.616427,0.675886,1.000000,0.604424
llama-2-70b-chat,0.512429,0.528964,0.447512,0.462562,0.604424,1.000000

method: pearson -- dataset: trivia_qa

model         human_sebhar
model
human_sebhar           1.0

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
METHOD: kendall
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
method: kendall -- dataset: bioasq

model         human_sebhar
model
human_sebhar           1.0

method: kendall -- dataset: squad

model,deberta,gpt-3.5,gpt-4,human_jansen,human_sebhar,llama-2-70b-chat
model,,,,,,
deberta,1.000000,0.653249,0.704658,0.587269,0.584407,0.482962
gpt-3.5,0.653249,1.000000,0.720901,0.668607,0.625011,0.531144
gpt-4,0.704658,0.720901,1.000000,0.726016,0.601175,0.457481
human_jansen,0.587269,0.668607,0.726016,1.000000,0.640126,0.465531
human_sebhar,0.584407,0.625011,0.601175,0.640126,1.000000,0.596928
llama-2-70b-chat,0.482962,0.531144,0.457481,0.465531,0.596928,1.000000

method: kendall -- dataset: trivia_qa

model         human_sebhar
model
human_sebhar           1.0

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
METHOD: spearman
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
method: spearman -- dataset: bioasq

model         human_sebhar
model
human_sebhar           1.0

method: spearman -- dataset: squad

model,deberta,gpt-3.5,gpt-4,human_jansen,human_sebhar,llama-2-70b-chat
model,,,,,,
deberta,1.000000,0.714222,0.749341,0.627699,0.633852,0.522131
gpt-3.5,0.714222,1.000000,0.760597,0.703120,0.675016,0.568904
gpt-4,0.749341,0.760597,1.000000,0.760488,0.645200,0.489619
human_jansen,0.627699,0.703120,0.760488,1.000000,0.693402,0.502430
human_sebhar,0.633852,0.675016,0.645200,0.693402,1.000000,0.634279
llama-2-70b-chat,0.522131,0.568904,0.489619,0.502430,0.634279,1.000000

method: spearman -- dataset: trivia_qa

model         human_sebhar
model
human_sebhar           1.0

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
METHOD: <function agreement at 0x7fed5ab62160>
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
method: <function agreement at 0x7fed5ab62160> -- dataset: bioasq

model         human_sebhar
model
human_sebhar           1.0

method: <function agreement at 0x7fed5ab62160> -- dataset: squad

model,deberta,gpt-3.5,gpt-4,human_jansen,human_sebhar,llama-2-70b-chat
model,,,,,,
deberta,1.00,0.59,0.69,0.65,0.59,0.50
gpt-3.5,0.59,1.00,0.76,0.76,0.59,0.67
gpt-4,0.69,0.76,1.00,0.77,0.53,0.59
human_jansen,0.65,0.76,0.77,1.00,0.64,0.62
human_sebhar,0.59,0.59,0.53,0.64,1.00,0.63
llama-2-70b-chat,0.50,0.67,0.59,0.62,0.63,1.00

method: <function agreement at 0x7fed5ab62160> -- dataset: trivia_qa

model         human_sebhar
model
human_sebhar           1.0

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
METHOD: <function cohen_kappa_score at 0x7fed6421d940>
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
method: <function cohen_kappa_score at 0x7fed6421d940> -- dataset: bioasq

model         human_sebhar
model
human_sebhar           1.0

method: <function cohen_kappa_score at 0x7fed6421d940> -- dataset: squad

model,deberta,gpt-3.5,gpt-4,human_jansen,human_sebhar,llama-2-70b-chat
model,,,,,,
deberta,1.000000,0.384846,0.532992,0.475734,0.390606,0.252951
gpt-3.5,0.384846,1.000000,0.613713,0.611964,0.354940,0.391368
gpt-4,0.532992,0.613713,1.000000,0.640849,0.311254,0.316781
human_jansen,0.475734,0.611964,0.640849,1.000000,0.428934,0.334384
human_sebhar,0.390606,0.354940,0.311254,0.428934,1.000000,0.350877
llama-2-70b-chat,0.252951,0.391368,0.316781,0.334384,0.350877,1.000000

method: <function cohen_kappa_score at 0x7fed6421d940> -- dataset: trivia_qa

model         human_sebhar
model
human_sebhar           1.0