In [1]:
%load_ext autoreload
%autoreload 2

from paper_utils import *
    
import os
os.chdir('../..')
from sklearn.metrics import cohen_kappa_score

```
# all runs at 8 generations (this is why we have to re-run some stuff)

'8ehbkd99': 'squad-8',
'5bqecpaq': 'squad-gpt3.5',


# rerun with 8 generations for llama and deberta
# (for both of them lax entailment was better than strict)
# 171235, 171236


# let's ignore the turbo variant
# 'ogqt6jkk': 'squad-gpt4t',


# could also use older results from here (2023-10-26-long-sentences-gpt4-and-llama-entailment)
# but they are over other datapoints which is suboptimal
# for deberta lax is better than strict
# 'ooslwgb9': '70b-squad-lax-deberta',
# 'iuh4ny1v': '70b-squad-strict-deberta',
# 'fbtvpw1y': '70b-squad-lax-llama',
# 'h5vd2k6a': '70b-squad-strict-llama',
# 'rzj7w9ei': '70b-squad-lax-gpt4',
# 'e0z3555u': '70b-squad-strict-gpt4',
```

In [5]:
# only here are questions/answers stored
base_run = 'uvfbxm6d'
base_config, base_generations = restore_file(base_run, filenames=['config.yaml', 'validation_generations.pkl'])

In [2]:
runs = {
    '8ehbkd99': ['squad-gpt4', ['config.yaml', 'uncertainty_measures.pkl', 'wandb-summary.json']],
    '5bqecpaq': ['squad-gpt35', ['config.yaml', 'uncertainty_measures.pkl', 'wandb-summary.json']],
    # 'xxxxx': ['squad-llama2', ['config.yaml', 'uncertainty_measures.pkl', 'wandb-summary.json']],
    # 'xxxxx': ['squad-deberta', ['config.yaml', 'uncertainty_measures.pkl', 'wandb-summary.json']],
}

all_configs, all_results, all_perfs = {}, {}, {}
for wandb_id, (name, files) in runs.items():
    all_configs[wandb_id], all_results[wandb_id], all_perfs[wandb_id] = restore_file(wandb_id, filenames=files)

In [17]:
active_run = '8ehbkd99'

N_ANNOTATIONS = 100
START_i = 0
END_i = 100
USE_N_GENERATIONS = 8

columns = ['index', 'data_id', 'wandb_id', 'dataset', 'entailment_mode', 'human_rater', 'entailment_ranking']

In [47]:
for i in range(START_i, END_i):
    key = list(base_generations.keys())[i]
    
    result = base_generations[key]
    print(80 * f'-')
    print(f'{i} / {key} -------- New Question ------')
    print('Q:', result['question'])
    print('True answer:', result['reference']['answers']['text'])
    print('Low-Temp Model response:', result['most_likely_answer']['response'])

    # NAIVE in-order printing
    # print('------')
    # for i, response in enumerate([r[0] for r in result['responses']][:USE_N_GENERATIONS]):
    #     print(f'{i}: {response}')
    # print('------')
    # active_results = all_results[active_run]
    # print(f"semantic_ids: {active_results['semantic_ids'][i]}")

    sids = np.array(active_results['semantic_ids'][i])

    all_sids, sids_counts = np.unique(sids, return_counts=True)
    sids_by_decreasing_count = all_sids[np.argsort(sids_counts)[::-1]]
    
    # NICER printing by semantic ID
    # sort clusters by size
    for i, uniq_sid in enumerate(sids_by_decreasing_count):
        # get indices of that semantic_id
        for idx in np.where(sids == uniq_sid)[0]:
            print(colorize(f'cluster {uniq_sid}: {result["responses"][idx][0]}', i))            

    print('-----')

--------------------------------------------------------------------------------
0 / 57338007d058e614000b5bdb -------- New Question ------
Q: What was Warsaw's population in 1901?
True answer: ['711,988', '711,988', '711,988']
Low-Temp Model response: According to the 1901 census, Warsaw's population was approximately 750,000 people.
cluster 2: According to the census of 1901, Warsaw's population was 750,000.
cluster 2: According to the 1901 census, Warsaw's population was approximately 750,000 people.
cluster 2: According to the census of 1901, Warsaw's population was 750,000.
cluster 5: According to the census of 1901, Warsaw had a population of 753,011.
cluster 4: In 1901, Warsaw's population was approximately 700,000.
cluster 3: According to the All-Russia Census of 1897, Warsaw's population was approximately 750,000 people.
cluster 1: According to the census of 1901, Warsaw's population was 817,000.
cluster 0: According to the census of 1901, Warsaw's population was 756,475.
-----
--------------------------------------------------------------------------------
1 / 571cc5c45efbb31900334dde -------- New Question ------
Q: When did O2 begin to acculturate in the atmosphere?
True answer: ['2.5 billion years ago', '2.5 billion years ago', 'about 2.5 billion years ago', 'about 2.5 billion years ago', '2.5 billion years ago during the Great Oxygenation Event']
Low-Temp Model response: O2 began to accumulate in the atmosphere around 2.7 billion years ago during the Great Oxygenation Event.
cluster 0: O2 began to accumulate in the atmosphere approximately 2.7 billion years ago during the Great Oxygenation Event.
cluster 0: Oxygen began to accumulate in the atmosphere around 2.7 billion years ago during the Great Oxygenation Event.
cluster 0: O2 began to accumulate in the atmosphere approximately 2.7 billion years ago during the Great Oxygenation Event.
cluster 0: O2 began to accumulate in the atmosphere around 2.7 billion years ago during the Great Oxygenation Event.
cluster 0: O2, or oxygen, began to acculturate in the atmosphere around 2.7 billion years ago during the Great Oxygenation Event.
cluster 0: O2 began to accumulate in the atmosphere around 2.7 billion years ago during the Great Oxygenation Event.
cluster 0: O2 began to accumulate in the atmosphere around 2.7 billion years ago during the Great Oxygenation Event.
cluster 1: O2 began to acculturate in the atmosphere around 2.5 billion years ago during the Great Oxygenation Event.
-----
--------------------------------------------------------------------------------
2 / 5733a5f54776f41900660f46 -------- New Question ------
Q: Who was Frédéric Chopin?
True answer: ['Famous musicians', 'musicians', 'Famous musicians']
Low-Temp Model response: Frédéric Chopin was a Polish composer and pianist of the Romantic era, known for his expressive and technically demanding piano music, particularly his nocturnes, waltzes, and preludes.
cluster 1: Frédéric Chopin was a Polish composer and pianist of the Romantic era who is widely regarded as one of the greatest composers of all time, known for his technically demanding and expressive piano music, including nocturnes, waltzes, preludes, and sonatas.
cluster 1: Frédéric Chopin was a Polish composer and virtuoso pianist of the Romantic era, known for his technically demanding and emotionally expressive piano music, including nocturnes, waltzes, preludes, and sonatas.
cluster 1: Frédéric Chopin was a Polish composer and virtuoso pianist of the Romantic era, known for his technically demanding and expressive piano music, particularly his nocturnes, waltzes, and preludes.
cluster 1: Frédéric Chopin was a Polish composer and pianist known for his expressive and technically demanding works for solo piano, particularly his nocturnes, waltzes, and preludes, and his innovative use of harmony and technique.
cluster 2: Frédéric Chopin was a Polish composer and pianist of the Romantic era known for his expressive, melancholic, and technically demanding piano music, including nocturnes, waltzes, preludes, and sonatas, and his piano concertos and chamber music are considered some of the greatest works of the 19th century.
cluster 2: Frédéric Chopin was a Polish composer and pianist of the Romantic era, known for his expressive and technically demanding piano music, particularly his nocturnes, waltzes, and preludes, which are considered among the most beautiful and influential works in the classical music repertoire.
cluster 3: Frédéric Chopin was a Polish composer and virtuoso pianist of the Romantic era.
cluster 0: Frédéric Chopin was a Polish-French Romantic composer and pianist known for his delicate, expressive, and technically demanding piano music.
-----
--------------------------------------------------------------------------------
3 / 5727dd2e4b864d1900163eba -------- New Question ------
Q: Harvard - Yale Regatta predates "The Game" by how many years?
True answer: ['23 years', '23', '23']
Low-Temp Model response: The Harvard-Yale Regatta predates "The Game" by 21 years, with the first regatta taking place in 1852 and the first football game between the two schools being played in 1875.
cluster 1: The Harvard-Yale Regatta predates "The Game" by 21 years, with the first regatta held in 1852 and the first football game played in 1875.
cluster 1: The Harvard-Yale Regatta predates "The Game" by 21 years, with the first regatta taking place in 1852 and the first football game between the two schools being played in 1875.
cluster 1: The Harvard-Yale Regatta predates "The Game" by 21 years, with the first regatta taking place in 1852 and the first football game between the two schools being played in 1875.
cluster 1: The Harvard-Yale Regatta predates "The Game" by 21 years, with the first regatta taking place in 1852 and the first football game between the two schools being played in 1875.
cluster 2: The Harvard-Yale Regatta predates "The Game" by 21 years, as the first regatta took place in 1852, while the first football game between the two schools was played in 1873.
cluster 2: The Harvard-Yale Regatta predates "The Game" by 21 years.
cluster 2: The Harvard-Yale Regatta predates "The Game" by 21 years.
cluster 0: The Harvard-Yale Regatta predates "The Game" by 24 years, with the first regatta taking place in 1852 and the first football game between the two schools being played in 1875.
-----
--------------------------------------------------------------------------------
4 / 5733fd66d058e614000b6737 -------- New Question ------
Q: Where did Moncalm slip away to attack, left largely unprotected?
True answer: ['Oswego', 'Oswego', 'Oswego', 'Oswego', 'Oswego']
Low-Temp Model response: Moncalm slipped away to attack the British left flank, which was left largely unprotected.
cluster 1: Moncalm slipped away to attack the largely unprotected British right flank.
cluster 1: Moncalm slipped away to attack the largely unprotected British right flank.
cluster 0: Moncalm slipped away to attack the British left flank, which was left largely unprotected.
cluster 0: Moncalm slipped away to attack the British left flank, which was left largely unprotected.
cluster 5: Moncalm slipped away to attack the British fleet off the coast of Quebec, which was left largely unprotected due to a lack of adequate defenses and the diversion of British forces to engage the French army at Quebec.
cluster 4: Moncalm slipped away to attack the British ships that were left largely unprotected in the channel between the North Shore and the Island of Orleans.
cluster 3: Moncalm slipped away to attack the British fleet, which was left largely unprotected at anchor in the harbor of Quebec.
cluster 2: Moncalm slipped away to attack the British at the Battle of Quebec.
-----
--------------------------------------------------------------------------------
5 / 572a064a3f37b3190047865f -------- New Question ------
Q: Indigenous territories are largely being destroyed in what two ways?
True answer: ['deforestation and ecocide', 'deforestation and ecocide', 'deforestation and ecocide']
Low-Temp Model response: Indigenous territories are largely being destroyed through the extraction of natural resources and the expansion of agriculture and urban areas.
cluster 0: Indigenous territories are being largely destroyed by both the physical appropriation of their lands for resource extraction, infrastructure, and settlements, and by the legal and political marginalization of Indigenous peoples, which denies them control over their own lands and resources.
cluster 0: Indigenous territories are largely being destroyed through the extractive activities of corporations and governments, such as mining, deforestation, and land grabbing, as well as through the imposition of capitalist economic systems and Western values that erode traditional ways of life and cultural practices.
cluster 6: Indigenous territories are being largely destroyed through the exploitation of their natural resources and the displacement of their communities.
cluster 5: Indigenous territories are largely being destroyed through the forced relocation of Indigenous peoples from their ancestral lands due to the extraction of natural resources and the creation of protected areas.
cluster 4: Indigenous territories are largely being destroyed through deforestation and land degradation, as well as resource extraction and infrastructure development.
cluster 3: Indigenous territories are largely being destroyed through the extraction of natural resources and the expansion of agriculture and urban areas.
cluster 2: Indigenous territories are being destroyed by the expansion of agriculture, mining, and energy projects, as well as by the illegal exploitation of natural resources such as timber and wildlife.
cluster 1: Indigenous territories are being largely destroyed through the exploitation of their natural resources and the forced assimilation of indigenous peoples.
-----
--------------------------------------------------------------------------------
6 / 57109275b654c5140001f9a3 -------- New Question ------
Q: When did the British defeat New France?
True answer: ['1759-60', '1759-60', '1759-60']
Low-Temp Model response: The British defeated New France in 1763, following the French and Indian War.
cluster 0: The British defeated New France in 1763, following the French and Indian War.
cluster 0: The British defeated New France in 1763, following the French and Indian War.
cluster 0: The British defeated New France in 1763, when they gained control of all French territory in North America following the French and Indian War.
cluster 0: The British defeated New France in 1763 when they won the French and Indian War.
cluster 0: The British defeated New France in 1763, following the signing of the Treaty of Paris, which ended the French and Indian War.
cluster 0: The British defeated New France in 1763 when the Treaty of Paris ended the French and Indian War, also known as the Seven Years' War.
cluster 0: The British defeated New France in 1763, when they won the French and Indian War (also known as the Seven Years' War).
cluster 1: The British defeated New France in 1759, following the French and Indian War.
-----
--------------------------------------------------------------------------------
7 / 572a12386aef051400155234 -------- New Question ------
Q: Drop in the blood levels of cortisol and epinephrine results in increase levels of what hormones?
True answer: ['leptin, pituitary growth hormone, and prolactin', 'leptin, pituitary growth hormone, and prolactin', 'leptin']
Low-Temp Model response: A decrease in cortisol and epinephrine levels results in an increase in serotonin and melatonin levels.
cluster 2: Drop in the blood levels of cortisol and epinephrine results in increase levels of serotonin and dopamine.
cluster 2: Drop in the blood levels of cortisol and epinephrine results in increase levels of serotonin and dopamine.
cluster 2: The drop in the blood levels of cortisol and epinephrine results in an increase in the levels of serotonin and dopamine.
cluster 2: A drop in the blood levels of cortisol and epinephrine results in an increase in the levels of serotonin and dopamine.
cluster 2: A decrease in cortisol and epinephrine levels results in an increase in serotonin and dopamine levels.
cluster 1: Drop in the blood levels of cortisol and epinephrine results in increase levels of insulin and growth hormone.
cluster 1: Drop in the blood levels of cortisol and epinephrine results in increase levels of insulin and human growth hormone.
cluster 0: A drop in blood levels of cortisol and epinephrine results in increased levels of insulin.
-----
--------------------------------------------------------------------------------
8 / 57309ef18ab72b1400f9c602 -------- New Question ------
Q: When was the military-political complex reflected upon within the scope of understanding imperialism?
True answer: ['the 1950s', '1950s', '1950s', '1950s', '1950s']
Low-Temp Model response: The military-political complex was reflected upon within the scope of understanding imperialism during the Cold War era, particularly in the 1960s and 1970s, when scholars and critics began to analyze the role of the military-industrial complex in shaping U.S. foreign policy and the global capitalist system.
cluster 1: The military-political complex was reflected upon within the scope of understanding imperialism in the 1960s and 1970s by scholars such as Chalmers Johnson, who argued that the complex was a key driver of US imperialism and that its influence had become increasingly pervasive in American society.
cluster 1: The military-political complex was reflected upon within the scope of understanding imperialism during the Cold War era, particularly in the 1960s and 1970s, through the works of scholars and critics such as Chalmers Johnson, who argued that the complex was a key driver of American imperialism and that its influence had to be understood in order to grasp the nature of US foreign policy.
cluster 1: The military-political complex was reflected upon within the scope of understanding imperialism during the Vietnam War, particularly through the writings of scholars such as Chalmers Johnson, who argued that the complex was a key factor in the United States' ability to maintain its empire and that its influence had become increasingly pernicious.
cluster 2: The military-political complex was reflected upon within the scope of understanding imperialism in the 1960s by scholars such as Chalmers Johnson, who argued that the complex was a major driver of US imperialism and that its influence had grown exponentially since World War II.
cluster 2: The military-political complex was reflected upon within the scope of understanding imperialism during the 1960s, particularly in the work of scholars such as Chalmers Johnson, who argued that the United States had become an empire in the guise of a republic, with a military-industrial complex that drove expansionist policies and perpetuated a system of global domination.
cluster 4: The military-political complex was reflected upon within the scope of understanding imperialism during the Cold War era, particularly in the 1960s and 1970s, as scholars and policymakers sought to understand the role of military power and its relationship to political and economic interests in the context of declining European empires and rising American hegemony.
cluster 3: The military-political complex was reflected upon within the scope of understanding imperialism during the Cold War era, particularly in the 1960s and 1970s, as scholars and policymakers sought to understand the role of military power in maintaining and expanding empires, as well as the ways in which military institutions and interests shaped foreign policy and international relations.
cluster 0: The military-political complex was reflected upon within the scope of understanding imperialism during the 1960s and 1970s, particularly in the work of scholars such as Chalmers Johnson and Edward Said, who argued that military power and political dominance were closely linked with economic interests and cultural domination in the context of imperialism.
-----
--------------------------------------------------------------------------------
9 / 57287d4a2ca10214002da3e7 -------- New Question ------
Q: What kind of division of power did Kublai's government have?
True answer: ['tripartite', 'tripartite division', 'tripartite']
Low-Temp Model response: Kublai's government had a centralized division of power, with the emperor holding supreme authority and power concentrated in the capital city of Khanbaliq.
cluster 7: Kublai's government had a centralized division of power, with the emperor holding supreme authority and power concentrated in the capital city of Khanbaliq (modern-day Beijing).
cluster 6: Kublai's government had a division of power between the emperor, the nobles, and the bureaucracy.
cluster 5: Kublai's government had a division of power between the military leaders, who were responsible for defense and expansion, and the civil officials, who were responsible for administration and taxation.
cluster 4: Kublai's government had a system of "dual government" in which civil and military affairs were separate and headed by different officials, with the civil administration controlled by the Chinese and the military controlled by the Mongols.
cluster 3: Kublai Khan's government had a centralized administrative structure with a division of power between civil and military authorities, with the Khan and his council of advisors holding supreme power.
cluster 2: Kublai Khan's government had a centralized division of power, with the emperor holding supreme authority and various departments and officials serving under him, including the chancellery, the secret police, and the military.
cluster 1: Kublai's government had a centralized division of power, with the emperor holding supreme authority and appointing officials to govern the various regions of the empire.
cluster 0: The government of Kublai Khan had a tripartite division of power between the emperor, the chancellor, and the military leaders, with the emperor holding supreme power but relying on the chancellor and military leaders to administer and enforce his rule.
-----
--------------------------------------------------------------------------------
10 / 571097baa58dae1900cd6a9b -------- New Question ------
Q: What church in Virginia is maintained by Huguenots as a historic shrine?
True answer: ['Manakin Episcopal Church', 'Manakin Episcopal Church', 'Manakin Episcopal Church']
Low-Temp Model response: The Huguenot Church in Manakin-Sabot, Virginia, is maintained by Huguenots as a historic shrine.
cluster 1: The Huguenot Church in Manakin, Virginia, is maintained by Huguenots as a historic shrine.
cluster 1: The Huguenot Church in Manakin, Virginia, is maintained by Huguenots as a historic shrine.
cluster 1: The Huguenot Church of Manakin, built in 1700, is maintained by Huguenots as a historic shrine in Virginia.
cluster 0: The Huguenot Church in Manakin-Sabot, Virginia, is maintained by Huguenots as a historic shrine.
cluster 0: The Huguenot Church in Manakin-Sabot, Virginia, is maintained by Huguenots as a historic shrine.
cluster 0: The Huguenot Church in Manakin-Sabot, Virginia, is maintained by Huguenots as a historic shrine.
cluster 2: The Huguenots maintained Swannanoa Church in Virginia as a historic shrine.
cluster 2: The Swannanoa Church in Rockbridge County, Virginia, is maintained by Huguenots as a historic shrine.
-----
--------------------------------------------------------------------------------
11 / 57300a9a04bcaa1900d77065 -------- New Question ------
Q: After 1935, who would be forbidden to enter Rhineland?
True answer: ['German army', 'German army', 'German army']

array([2, 5, 4, 3, 1, 0])

In [33]:
def colorize(text, color=0):
    i2c = {i: f"\x1b[{a}" for i, a in enumerate([
    '31m', '33m', '34m', '35m', '36m', '37m', '38m', '39m'])}
    r = "\x1b[0m"

    return i2c[color] + text + r

In [ ]:


runs_data = []

for i in range(START_i, END_i):

    
    for run in runs:
        if runs[run][1][1] == 'uncertainty_measures.pkl':
            accuracy = 1 - all_results[run]['validation_is_false'][i]
        elif runs[run][1][1] == 'validation_generations.pkl':
            accuracy = result['most_likely_answer']['accuracy']
        else:
            raise
        accuracy = int(accuracy)
        dataset, metric = runs[run][0].split('-')
        run_data = [i, key, run, dataset, metric, accuracy]
        print(f'Accuracy {metric}: {accuracy}')

        if metric in WRITE_AUTOMATED_METRICS:
            runs_data.append(run_data)

        print(','.join([str(i) for i in run_data]))

    print(f'Accuracy human: ???')
    for user in users:
        runs_data.append([i, key, run, dataset, f'human_{user}', 'FILL_IN'])

In [22]:
users = ['jansen', 'sebhar', 'kunda']

# Enable this to also get gpt/llama2 truth data in the CSV
WRITE_AUTOMATED_METRICS = ['f1']

In [23]:
columns = ['index', 'data_id', 'wandb_id', 'dataset', 'truth_metric', 'truth_value']

runs_data = []

for i in range(START_i, END_i):

    key = list(all_results[active_run].keys())[i]
    
    result = all_results[active_run][key]
    print(80 * f'-')
    print(f'{i} / {key} -------- New Question ------')
    print('Q:', result['question'])
    print('True answer:', result['reference']['answers']['text'])
    print('Model response:', result['most_likely_answer']['response'])
    
    for run in runs:
        if runs[run][1][1] == 'uncertainty_measures.pkl':
            accuracy = 1 - all_results[run]['validation_is_false'][i]
        elif runs[run][1][1] == 'validation_generations.pkl':
            accuracy = result['most_likely_answer']['accuracy']
        else:
            raise
        accuracy = int(accuracy)
        dataset, metric = runs[run][0].split('-')
        run_data = [i, key, run, dataset, metric, accuracy]
        print(f'Accuracy {metric}: {accuracy}')

        if metric in WRITE_AUTOMATED_METRICS:
            runs_data.append(run_data)

        print(','.join([str(i) for i in run_data]))

    print(f'Accuracy human: ???')
    for user in users:
        runs_data.append([i, key, run, dataset, f'human_{user}', 'FILL_IN'])

--------------------------------------------------------------------------------
0 / 57338007d058e614000b5bdb -------- New Question ------
Q: What was Warsaw's population in 1901?
True answer: ['711,988', '711,988', '711,988']
Model response: According to the 1901 census, Warsaw's population was approximately 750,000 people.
Accuracy llama2: 0
0,57338007d058e614000b5bdb,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
0,57338007d058e614000b5bdb,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
0,57338007d058e614000b5bdb,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
0,57338007d058e614000b5bdb,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
1 / 571cc5c45efbb31900334dde -------- New Question ------
Q: When did O2 begin to acculturate in the atmosphere?
True answer: ['2.5 billion years ago', '2.5 billion years ago', 'about 2.5 billion years ago', 'about 2.5 billion years ago', '2.5 billion years ago during the Great Oxygenation Event']
Model response: O2 began to accumulate in the atmosphere around 2.7 billion years ago during the Great Oxygenation Event.
Accuracy llama2: 0
1,571cc5c45efbb31900334dde,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
1,571cc5c45efbb31900334dde,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
1,571cc5c45efbb31900334dde,6cxqnx2u,squad,gpt4,0
Accuracy f1: 1
1,571cc5c45efbb31900334dde,dcnndvny,squad,f1,1
Accuracy human: ???
--------------------------------------------------------------------------------
2 / 5733a5f54776f41900660f46 -------- New Question ------
Q: Who was Frédéric Chopin?
True answer: ['Famous musicians', 'musicians', 'Famous musicians']
Model response: Frédéric Chopin was a Polish composer and pianist of the Romantic era, known for his expressive and technically demanding piano music, particularly his nocturnes, waltzes, and preludes.
Accuracy llama2: 0
2,5733a5f54776f41900660f46,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 1
2,5733a5f54776f41900660f46,m3y3x605,squad,gpt35,1
Accuracy gpt4: 0
2,5733a5f54776f41900660f46,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
2,5733a5f54776f41900660f46,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
3 / 5727dd2e4b864d1900163eba -------- New Question ------
Q: Harvard - Yale Regatta predates "The Game" by how many years?
True answer: ['23 years', '23', '23']
Model response: The Harvard-Yale Regatta predates "The Game" by 21 years, with the first regatta taking place in 1852 and the first football game between the two schools being played in 1875.
Accuracy llama2: 0
3,5727dd2e4b864d1900163eba,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
3,5727dd2e4b864d1900163eba,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
3,5727dd2e4b864d1900163eba,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
3,5727dd2e4b864d1900163eba,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
4 / 5733fd66d058e614000b6737 -------- New Question ------
Q: Where did Moncalm slip away to attack, left largely unprotected?
True answer: ['Oswego', 'Oswego', 'Oswego', 'Oswego', 'Oswego']
Model response: Moncalm slipped away to attack the British left flank, which was left largely unprotected.
Accuracy llama2: 0
4,5733fd66d058e614000b6737,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 1
4,5733fd66d058e614000b6737,m3y3x605,squad,gpt35,1
Accuracy gpt4: 0
4,5733fd66d058e614000b6737,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
4,5733fd66d058e614000b6737,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
5 / 572a064a3f37b3190047865f -------- New Question ------
Q: Indigenous territories are largely being destroyed in what two ways?
True answer: ['deforestation and ecocide', 'deforestation and ecocide', 'deforestation and ecocide']
Model response: Indigenous territories are largely being destroyed through the extraction of natural resources and the expansion of agriculture and urban areas.
Accuracy llama2: 0
5,572a064a3f37b3190047865f,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
5,572a064a3f37b3190047865f,m3y3x605,squad,gpt35,0
Accuracy gpt4: 1
5,572a064a3f37b3190047865f,6cxqnx2u,squad,gpt4,1
Accuracy f1: 0
5,572a064a3f37b3190047865f,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
6 / 57109275b654c5140001f9a3 -------- New Question ------
Q: When did the British defeat New France?
True answer: ['1759-60', '1759-60', '1759-60']
Model response: The British defeated New France in 1763, following the French and Indian War.
Accuracy llama2: 0
6,57109275b654c5140001f9a3,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
6,57109275b654c5140001f9a3,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
6,57109275b654c5140001f9a3,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
6,57109275b654c5140001f9a3,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
7 / 572a12386aef051400155234 -------- New Question ------
Q: Drop in the blood levels of cortisol and epinephrine results in increase levels of what hormones?
True answer: ['leptin, pituitary growth hormone, and prolactin', 'leptin, pituitary growth hormone, and prolactin', 'leptin']
Model response: A decrease in cortisol and epinephrine levels results in an increase in serotonin and melatonin levels.
Accuracy llama2: 0
7,572a12386aef051400155234,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
7,572a12386aef051400155234,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
7,572a12386aef051400155234,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
7,572a12386aef051400155234,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
8 / 57309ef18ab72b1400f9c602 -------- New Question ------
Q: When was the military-political complex reflected upon within the scope of understanding imperialism?
True answer: ['the 1950s', '1950s', '1950s', '1950s', '1950s']
Model response: The military-political complex was reflected upon within the scope of understanding imperialism during the Cold War era, particularly in the 1960s and 1970s, when scholars and critics began to analyze the role of the military-industrial complex in shaping U.S. foreign policy and the global capitalist system.
Accuracy llama2: 0
8,57309ef18ab72b1400f9c602,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
8,57309ef18ab72b1400f9c602,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
8,57309ef18ab72b1400f9c602,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
8,57309ef18ab72b1400f9c602,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
9 / 57287d4a2ca10214002da3e7 -------- New Question ------
Q: What kind of division of power did Kublai's government have?
True answer: ['tripartite', 'tripartite division', 'tripartite']
Model response: Kublai's government had a centralized division of power, with the emperor holding supreme authority and power concentrated in the capital city of Khanbaliq.
Accuracy llama2: 0
9,57287d4a2ca10214002da3e7,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
9,57287d4a2ca10214002da3e7,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
9,57287d4a2ca10214002da3e7,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
9,57287d4a2ca10214002da3e7,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
10 / 571097baa58dae1900cd6a9b -------- New Question ------
Q: What church in Virginia is maintained by Huguenots as a historic shrine?
True answer: ['Manakin Episcopal Church', 'Manakin Episcopal Church', 'Manakin Episcopal Church']
Model response: The Huguenot Church in Manakin-Sabot, Virginia, is maintained by Huguenots as a historic shrine.
Accuracy llama2: 1
10,571097baa58dae1900cd6a9b,uvfbxm6d,squad,llama2,1
Accuracy gpt35: 1
10,571097baa58dae1900cd6a9b,m3y3x605,squad,gpt35,1
Accuracy gpt4: 1
10,571097baa58dae1900cd6a9b,6cxqnx2u,squad,gpt4,1
Accuracy f1: 0
10,571097baa58dae1900cd6a9b,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
11 / 57300a9a04bcaa1900d77065 -------- New Question ------
Q: After 1935, who would be forbidden to enter Rhineland?
True answer: ['German army', 'German army', 'German army']
Model response: After 1935, military forces from any country except Germany would be forbidden to enter Rhineland under the terms of the Treaty of Versailles and the subsequent Rhineland Pact.
Accuracy llama2: 0
11,57300a9a04bcaa1900d77065,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 1
11,57300a9a04bcaa1900d77065,m3y3x605,squad,gpt35,1
Accuracy gpt4: 0
11,57300a9a04bcaa1900d77065,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
11,57300a9a04bcaa1900d77065,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
12 / 572826634b864d19001645bf -------- New Question ------
Q: How many residents were recorded in the 2010 census of Jacksonville?
True answer: ['821,784', '821,784', '821,784']
Model response: According to the 2010 census, Jacksonville had a population of approximately 821,785 residents.
Accuracy llama2: 0
12,572826634b864d19001645bf,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
12,572826634b864d19001645bf,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
12,572826634b864d19001645bf,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
12,572826634b864d19001645bf,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
13 / 572fb059947a6a140053cb81 -------- New Question ------
Q: What  former administrative building was used for the MSP's offices?
True answer: ['Lothian Regional Council', 'Lothian Regional Council', 'Lothian Regional Council on George IV Bridge']
Model response: The MSP's offices were located in the former Michigan Bell Building.
Accuracy llama2: 0
13,572fb059947a6a140053cb81,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
13,572fb059947a6a140053cb81,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
13,572fb059947a6a140053cb81,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
13,572fb059947a6a140053cb81,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
14 / 5729ea263f37b319004785bd -------- New Question ------
Q: A satellite that measured the amount of dust going to the Amazon was named what?
True answer: ['CALIPSO', 'CALIPSO', 'CALIPSO']
Model response: The satellite that measured the amount of dust going to the Amazon was named the Cloud-Aerosol Lidar and Infrared Pathfinder Satellite Observations (CALIPSO).
Accuracy llama2: 1
14,5729ea263f37b319004785bd,uvfbxm6d,squad,llama2,1
Accuracy gpt35: 1
14,5729ea263f37b319004785bd,m3y3x605,squad,gpt35,1
Accuracy gpt4: 1
14,5729ea263f37b319004785bd,6cxqnx2u,squad,gpt4,1
Accuracy f1: 0
14,5729ea263f37b319004785bd,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
15 / 57264d58f1498d1400e8db7c -------- New Question ------
Q: What percent of untreated victims of the plague die within 8 days?
True answer: ['80 percent', '80', '80']
Model response: Sixty percent of untreated victims of the plague die within 8 days.
Accuracy llama2: 0
15,57264d58f1498d1400e8db7c,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
15,57264d58f1498d1400e8db7c,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
15,57264d58f1498d1400e8db7c,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
15,57264d58f1498d1400e8db7c,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
16 / 5727502f708984140094dc09 -------- New Question ------
Q: Who studies the expected monetary flow over the life of the project and to monitor the payouts throughout the process?
True answer: ['Accountants', 'Accountants', 'Accountants']
Model response: The financial analyst studies the expected monetary flow over the life of the project and monitors the payouts throughout the process.
Accuracy llama2: 0
16,5727502f708984140094dc09,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 1
16,5727502f708984140094dc09,m3y3x605,squad,gpt35,1
Accuracy gpt4: 1
16,5727502f708984140094dc09,6cxqnx2u,squad,gpt4,1
Accuracy f1: 0
16,5727502f708984140094dc09,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
17 / 57097c8fed30961900e841f2 -------- New Question ------
Q: What did Alec Shelbrooke propose payments of benefits to be made on?
True answer: ['Welfare Cash Card', 'Welfare Cash Card', 'Welfare Cash Card']
Model response: Alec Shelbrooke proposed that payments of benefits be made on a Universal Credit system, where all benefits would be combined into a single payment, simplifying the welfare system and allowing people to manage their own finances more effectively.
Accuracy llama2: 0
17,57097c8fed30961900e841f2,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
17,57097c8fed30961900e841f2,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
17,57097c8fed30961900e841f2,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
17,57097c8fed30961900e841f2,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
18 / 57264a8cdd62a815002e808f -------- New Question ------
Q: For each of the 28 member states, how many Commissioner's are represented for each one?
True answer: ['one Commissioner for each of the 28 member states', 'one', 'one', 'one']
Model response: Each of the 28 member states of the European Union has one Commissioner representing them in the European Commission.
Accuracy llama2: 1
18,57264a8cdd62a815002e808f,uvfbxm6d,squad,llama2,1
Accuracy gpt35: 1
18,57264a8cdd62a815002e808f,m3y3x605,squad,gpt35,1
Accuracy gpt4: 1
18,57264a8cdd62a815002e808f,6cxqnx2u,squad,gpt4,1
Accuracy f1: 1
18,57264a8cdd62a815002e808f,dcnndvny,squad,f1,1
Accuracy human: ???
--------------------------------------------------------------------------------
19 / 57302bd0b2c2fd14005689de -------- New Question ------
Q: How many people did the Islamic State control the territory of as of March 2015?
True answer: ['ten million', 'ten million', 'ten million']
Model response: As of March 2015, the Islamic State controlled the territory of approximately 9 million people across Iraq and Syria.
Accuracy llama2: 0
19,57302bd0b2c2fd14005689de,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
19,57302bd0b2c2fd14005689de,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
19,57302bd0b2c2fd14005689de,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
19,57302bd0b2c2fd14005689de,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
20 / 572ff12e04bcaa1900d76f03 -------- New Question ------
Q: What is the section of the Rhine Gorge recognized by UNESCO called?
True answer: ['Romantic Rhine', 'the Romantic Rhine', 'the Romantic Rhine']
Model response: The section of the Rhine Gorge recognized by UNESCO is called the "Upper Middle Rhine Valley" or "Oberes Mittelrheintal" in German.
Accuracy llama2: 0
20,572ff12e04bcaa1900d76f03,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
20,572ff12e04bcaa1900d76f03,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
20,572ff12e04bcaa1900d76f03,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
20,572ff12e04bcaa1900d76f03,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
21 / 57297ed93f37b3190047845f -------- New Question ------
Q: What is one straightforward case of a probabilistic test?
True answer: ['the Fermat primality test,', 'Fermat primality test', 'Fermat primality test', 'Fermat primality test', 'the Fermat primality test']
Model response: A straightforward case of a probabilistic test is the coin flip test, where a coin is flipped multiple times and the probability of obtaining a certain number of heads or tails is calculated to determine whether the coin is fair or biased.
Accuracy llama2: 0
21,57297ed93f37b3190047845f,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
21,57297ed93f37b3190047845f,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
21,57297ed93f37b3190047845f,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
21,57297ed93f37b3190047845f,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
22 / 56e1c7e2cd28a01900c67b75 -------- New Question ------
Q: What is responsible for constraining P according to the time hierarchy theorem?
True answer: ['EXPTIME', 'EXPTIME', 'EXPTIME']
Model response: The time hierarchy theorem states that P is constrained by the logarithmic time hierarchy, which means that the running time of algorithms in P increases logarithmically with the size of the input.
Accuracy llama2: 1
22,56e1c7e2cd28a01900c67b75,uvfbxm6d,squad,llama2,1
Accuracy gpt35: 0
22,56e1c7e2cd28a01900c67b75,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
22,56e1c7e2cd28a01900c67b75,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
22,56e1c7e2cd28a01900c67b75,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
23 / 570d2c20fed7b91900d45ca9 -------- New Question ------
Q: Where was Victoria first set to be located in Australia?
True answer: ['New South Wales', 'New South Wales', 'New South Wales']
Model response: Victoria was first set to be located in Australia at Port Phillip, which was later renamed Melbourne in 1837.
Accuracy llama2: 0
23,570d2c20fed7b91900d45ca9,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
23,570d2c20fed7b91900d45ca9,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
23,570d2c20fed7b91900d45ca9,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
23,570d2c20fed7b91900d45ca9,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
24 / 5727e6cbff5b5019007d97f0 -------- New Question ------
Q: In order to be considered in the top percentile, a person would need to amass how much money each year?
True answer: ['$759,900', '$759,900', '$759,900']
Model response: To be considered in the top percentile, a person would need to amass $1.5 million or more each year.
Accuracy llama2: 0
24,5727e6cbff5b5019007d97f0,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
24,5727e6cbff5b5019007d97f0,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
24,5727e6cbff5b5019007d97f0,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
24,5727e6cbff5b5019007d97f0,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
25 / 56e1ee4de3433e1400423214 -------- New Question ------
Q: What evidence between and among complexity classes would signify a theoretical watershed for complexity theory?
True answer: ['Proving that any of these classes are unequal', 'Proving that any of these classes are unequal', 'Proving that any of these classes are unequal']
Model response: A proof that NP is not equal to co-NP, or a proof that P is not equal to NP, would signify a theoretical watershed for complexity theory.
Accuracy llama2: 0
25,56e1ee4de3433e1400423214,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 1
25,56e1ee4de3433e1400423214,m3y3x605,squad,gpt35,1
Accuracy gpt4: 1
25,56e1ee4de3433e1400423214,6cxqnx2u,squad,gpt4,1
Accuracy f1: 0
25,56e1ee4de3433e1400423214,dcnndvny,squad,f1,0
Accuracy human: ???
--------------------------------------------------------------------------------
26 / 56e1a564cd28a01900c67a48 -------- New Question ------
Q: Whose thesis states that the solution to a problem is solvable with reasonable resources assuming it allows for a polynomial time algorithm?
True answer: ["Cobham's thesis", "Cobham's", 'Cobham']
Model response: Stephen Cook's thesis states that the solution to a problem is solvable with reasonable resources assuming it allows for a polynomial time algorithm.
Accuracy llama2: 0
26,56e1a564cd28a01900c67a48,uvfbxm6d,squad,llama2,0
Accuracy gpt35: 0
26,56e1a564cd28a01900c67a48,m3y3x605,squad,gpt35,0
Accuracy gpt4: 0
26,56e1a564cd28a01900c67a48,6cxqnx2u,squad,gpt4,0
Accuracy f1: 0
26,56e1a564cd28a01900c67a48,dcnndvny,squad,f1,0
Accuracy human: ???

In [24]:
# [DONE] Use this to set up the CSV that you fill values in
print(pd.DataFrame(runs_data, columns=columns).sort_values(['truth_metric', 'index']).to_csv(index=False))

index,data_id,wandb_id,dataset,truth_metric,truth_value
0,57338007d058e614000b5bdb,dcnndvny,squad,f1,0
1,571cc5c45efbb31900334dde,dcnndvny,squad,f1,1
2,5733a5f54776f41900660f46,dcnndvny,squad,f1,0
3,5727dd2e4b864d1900163eba,dcnndvny,squad,f1,0
4,5733fd66d058e614000b6737,dcnndvny,squad,f1,0
5,572a064a3f37b3190047865f,dcnndvny,squad,f1,0
6,57109275b654c5140001f9a3,dcnndvny,squad,f1,0
7,572a12386aef051400155234,dcnndvny,squad,f1,0
8,57309ef18ab72b1400f9c602,dcnndvny,squad,f1,0
9,57287d4a2ca10214002da3e7,dcnndvny,squad,f1,0
10,571097baa58dae1900cd6a9b,dcnndvny,squad,f1,0
11,57300a9a04bcaa1900d77065,dcnndvny,squad,f1,0
12,572826634b864d19001645bf,dcnndvny,squad,f1,0
13,572fb059947a6a140053cb81,dcnndvny,squad,f1,0
14,5729ea263f37b319004785bd,dcnndvny,squad,f1,0
15,57264d58f1498d1400e8db7c,dcnndvny,squad,f1,0
16,5727502f708984140094dc09,dcnndvny,squad,f1,0
17,57097c8fed30961900e841f2,dcnndvny,squad,f1,0
18,57264a8cdd62a815002e808f,dcnndvny,squad,f1,1
19,57302bd0b2c2fd14005689de,dcnndvny,squad,f1,0
20,572ff12e04bcaa1900d76f03,dcnndvny,squad,f1,0
21,57297ed93f37b3190047845f,dcnndvny,squad,f1,0
22,56e1c7e2cd28a01900c67b75,dcnndvny,squad,f1,0
23,570d2c20fed7b91900d45ca9,dcnndvny,squad,f1,0
24,5727e6cbff5b5019007d97f0,dcnndvny,squad,f1,0
25,56e1ee4de3433e1400423214,dcnndvny,squad,f1,0
26,56e1a564cd28a01900c67a48,dcnndvny,squad,f1,0
27,57332a734776f41900660729,dcnndvny,squad,f1,0
28,572a18a4af94a219006aa7e2,dcnndvny,squad,f1,0
29,5728e3c33acd2414000e0132,dcnndvny,squad,f1,0
30,57265526708984140094c2c1,dcnndvny,squad,f1,0
31,5705ffde52bb891400689786,dcnndvny,squad,f1,0
32,57275411dd62a815002e9b33,dcnndvny,squad,f1,0
33,5726fa525951b619008f83f9,dcnndvny,squad,f1,0
34,57303048947a6a140053d256,dcnndvny,squad,f1,0
35,57287f6a3acd2414000dfa52,dcnndvny,squad,f1,0
36,5725bcb6271a42140099d0eb,dcnndvny,squad,f1,0
37,56e1aff7cd28a01900c67a6c,dcnndvny,squad,f1,0
38,5726baf2dd62a815002e8e75,dcnndvny,squad,f1,0
39,57115b2850c2381900b54a80,dcnndvny,squad,f1,0
40,57264fe65951b619008f6fa4,dcnndvny,squad,f1,0
41,5726a5525951b619008f78de,dcnndvny,squad,f1,0
42,572681c1dd62a815002e8799,dcnndvny,squad,f1,0
43,57265e97708984140094c3c7,dcnndvny,squad,f1,0
44,5727dc473acd2414000dee45,dcnndvny,squad,f1,1
45,573010fab2c2fd14005687d7,dcnndvny,squad,f1,0
46,572fe288a23a5019007fcadb,dcnndvny,squad,f1,0
47,572fbea404bcaa1900d76c5c,dcnndvny,squad,f1,0
48,572fd264b2c2fd14005684ad,dcnndvny,squad,f1,0
49,5729f3883f37b319004785f1,dcnndvny,squad,f1,0
50,572fe60fb2c2fd140056858f,dcnndvny,squad,f1,0
51,56e1ee4de3433e1400423211,dcnndvny,squad,f1,0
52,571154c72419e3140095558b,dcnndvny,squad,f1,0
53,56de16ca4396321400ee25c8,dcnndvny,squad,f1,0
54,57114f0050c2381900b54a66,dcnndvny,squad,f1,0
55,56e1ce08e3433e14004231a5,dcnndvny,squad,f1,0
56,5706139252bb891400689864,dcnndvny,squad,f1,0
57,5733e8ae4776f419006614a7,dcnndvny,squad,f1,0
58,57265526708984140094c2bf,dcnndvny,squad,f1,0
59,5711541350c2381900b54a72,dcnndvny,squad,f1,0
60,5733fd66d058e614000b6735,dcnndvny,squad,f1,0
61,5727da564b864d1900163e8f,dcnndvny,squad,f1,0
62,57096f37200fba1400367fe6,dcnndvny,squad,f1,0
63,56e181d9e3433e1400422fa3,dcnndvny,squad,f1,0
64,573368044776f41900660a2a,dcnndvny,squad,f1,0
65,572a1fe16aef0514001552d2,dcnndvny,squad,f1,0
66,57336755d058e614000b5a3f,dcnndvny,squad,f1,0
67,5725bbec271a42140099d0d2,dcnndvny,squad,f1,0
68,57302efe04bcaa1900d772f7,dcnndvny,squad,f1,0
69,572a05eb3f37b31900478653,dcnndvny,squad,f1,0
70,570602fa52bb89140068979e,dcnndvny,squad,f1,0
71,572f59b4a23a5019007fc58b,dcnndvny,squad,f1,0
72,5725b76389a1e219009abd4b,dcnndvny,squad,f1,0
73,57060eaf75f01819005e7913,dcnndvny,squad,f1,0
74,573749741c4567190057445e,dcnndvny,squad,f1,0
75,5727aec03acd2414000de995,dcnndvny,squad,f1,0
76,57300c67947a6a140053cff2,dcnndvny,squad,f1,0
77,57286192ff5b5019007da1de,dcnndvny,squad,f1,0
78,572870b2ff5b5019007da224,dcnndvny,squad,f1,0
79,57281c594b864d19001644a5,dcnndvny,squad,f1,0
80,57268d2ddd62a815002e8951,dcnndvny,squad,f1,0
81,56e202e9e3433e1400423243,dcnndvny,squad,f1,0
82,572824f13acd2414000df593,dcnndvny,squad,f1,0
83,573081c2069b531400832135,dcnndvny,squad,f1,0
84,572863c72ca10214002da2d7,dcnndvny,squad,f1,0
85,5728f9882ca10214002dab5c,dcnndvny,squad,f1,0
86,57377aac1c4567190057447a,dcnndvny,squad,f1,0
87,573786b51c4567190057448f,dcnndvny,squad,f1,0
88,57274b35f1498d1400e8f5d4,dcnndvny,squad,f1,0
89,57338160d058e614000b5bf9,dcnndvny,squad,f1,0
90,57097d63ed30961900e841fd,dcnndvny,squad,f1,0
91,571a484210f8ca1400304fbf,dcnndvny,squad,f1,0
92,5725f7cd38643c19005acf25,dcnndvny,squad,f1,0
93,5725cfd0271a42140099d226,dcnndvny,squad,f1,0
94,57264efddd62a815002e8138,dcnndvny,squad,f1,0
95,57107d73b654c5140001f91e,dcnndvny,squad,f1,0
96,5728661e2ca10214002da2e9,dcnndvny,squad,f1,0
97,56e17a7ccd28a01900c679a1,dcnndvny,squad,f1,0
98,571c97e2dd7acb1400e4c121,dcnndvny,squad,f1,0
99,5726431aec44d21400f3dd13,dcnndvny,squad,f1,0
0,57338007d058e614000b5bdb,dcnndvny,squad,human_kunda,FILL_IN
1,571cc5c45efbb31900334dde,dcnndvny,squad,human_kunda,FILL_IN
2,5733a5f54776f41900660f46,dcnndvny,squad,human_kunda,FILL_IN
3,5727dd2e4b864d1900163eba,dcnndvny,squad,human_kunda,FILL_IN
4,5733fd66d058e614000b6737,dcnndvny,squad,human_kunda,FILL_IN
5,572a064a3f37b3190047865f,dcnndvny,squad,human_kunda,FILL_IN
6,57109275b654c5140001f9a3,dcnndvny,squad,human_kunda,FILL_IN
7,572a12386aef051400155234,dcnndvny,squad,human_kunda,FILL_IN
8,57309ef18ab72b1400f9c602,dcnndvny,squad,human_kunda,FILL_IN
9,57287d4a2ca10214002da3e7,dcnndvny,squad,human_kunda,FILL_IN
10,571097baa58dae1900cd6a9b,dcnndvny,squad,human_kunda,FILL_IN
11,57300a9a04bcaa1900d77065,dcnndvny,squad,human_kunda,FILL_IN
12,572826634b864d19001645bf,dcnndvny,squad,human_kunda,FILL_IN
13,572fb059947a6a140053cb81,dcnndvny,squad,human_kunda,FILL_IN
14,5729ea263f37b319004785bd,dcnndvny,squad,human_kunda,FILL_IN
15,57264d58f1498d1400e8db7c,dcnndvny,squad,human_kunda,FILL_IN
16,5727502f708984140094dc09,dcnndvny,squad,human_kunda,FILL_IN
17,57097c8fed30961900e841f2,dcnndvny,squad,human_kunda,FILL_IN
18,57264a8cdd62a815002e808f,dcnndvny,squad,human_kunda,FILL_IN
19,57302bd0b2c2fd14005689de,dcnndvny,squad,human_kunda,FILL_IN
20,572ff12e04bcaa1900d76f03,dcnndvny,squad,human_kunda,FILL_IN
21,57297ed93f37b3190047845f,dcnndvny,squad,human_kunda,FILL_IN
22,56e1c7e2cd28a01900c67b75,dcnndvny,squad,human_kunda,FILL_IN
23,570d2c20fed7b91900d45ca9,dcnndvny,squad,human_kunda,FILL_IN
24,5727e6cbff5b5019007d97f0,dcnndvny,squad,human_kunda,FILL_IN
25,56e1ee4de3433e1400423214,dcnndvny,squad,human_kunda,FILL_IN
26,56e1a564cd28a01900c67a48,dcnndvny,squad,human_kunda,FILL_IN
27,57332a734776f41900660729,dcnndvny,squad,human_kunda,FILL_IN
28,572a18a4af94a219006aa7e2,dcnndvny,squad,human_kunda,FILL_IN
29,5728e3c33acd2414000e0132,dcnndvny,squad,human_kunda,FILL_IN
30,57265526708984140094c2c1,dcnndvny,squad,human_kunda,FILL_IN
31,5705ffde52bb891400689786,dcnndvny,squad,human_kunda,FILL_IN
32,57275411dd62a815002e9b33,dcnndvny,squad,human_kunda,FILL_IN
33,5726fa525951b619008f83f9,dcnndvny,squad,human_kunda,FILL_IN
34,57303048947a6a140053d256,dcnndvny,squad,human_kunda,FILL_IN
35,57287f6a3acd2414000dfa52,dcnndvny,squad,human_kunda,FILL_IN
36,5725bcb6271a42140099d0eb,dcnndvny,squad,human_kunda,FILL_IN
37,56e1aff7cd28a01900c67a6c,dcnndvny,squad,human_kunda,FILL_IN
38,5726baf2dd62a815002e8e75,dcnndvny,squad,human_kunda,FILL_IN
39,57115b2850c2381900b54a80,dcnndvny,squad,human_kunda,FILL_IN
40,57264fe65951b619008f6fa4,dcnndvny,squad,human_kunda,FILL_IN
41,5726a5525951b619008f78de,dcnndvny,squad,human_kunda,FILL_IN
42,572681c1dd62a815002e8799,dcnndvny,squad,human_kunda,FILL_IN
43,57265e97708984140094c3c7,dcnndvny,squad,human_kunda,FILL_IN
44,5727dc473acd2414000dee45,dcnndvny,squad,human_kunda,FILL_IN
45,573010fab2c2fd14005687d7,dcnndvny,squad,human_kunda,FILL_IN
46,572fe288a23a5019007fcadb,dcnndvny,squad,human_kunda,FILL_IN
47,572fbea404bcaa1900d76c5c,dcnndvny,squad,human_kunda,FILL_IN
48,572fd264b2c2fd14005684ad,dcnndvny,squad,human_kunda,FILL_IN
49,5729f3883f37b319004785f1,dcnndvny,squad,human_kunda,FILL_IN
50,572fe60fb2c2fd140056858f,dcnndvny,squad,human_kunda,FILL_IN
51,56e1ee4de3433e1400423211,dcnndvny,squad,human_kunda,FILL_IN
52,571154c72419e3140095558b,dcnndvny,squad,human_kunda,FILL_IN
53,56de16ca4396321400ee25c8,dcnndvny,squad,human_kunda,FILL_IN
54,57114f0050c2381900b54a66,dcnndvny,squad,human_kunda,FILL_IN
55,56e1ce08e3433e14004231a5,dcnndvny,squad,human_kunda,FILL_IN
56,5706139252bb891400689864,dcnndvny,squad,human_kunda,FILL_IN
57,5733e8ae4776f419006614a7,dcnndvny,squad,human_kunda,FILL_IN
58,57265526708984140094c2bf,dcnndvny,squad,human_kunda,FILL_IN
59,5711541350c2381900b54a72,dcnndvny,squad,human_kunda,FILL_IN
60,5733fd66d058e614000b6735,dcnndvny,squad,human_kunda,FILL_IN
61,5727da564b864d1900163e8f,dcnndvny,squad,human_kunda,FILL_IN
62,57096f37200fba1400367fe6,dcnndvny,squad,human_kunda,FILL_IN
63,56e181d9e3433e1400422fa3,dcnndvny,squad,human_kunda,FILL_IN
64,573368044776f41900660a2a,dcnndvny,squad,human_kunda,FILL_IN
65,572a1fe16aef0514001552d2,dcnndvny,squad,human_kunda,FILL_IN
66,57336755d058e614000b5a3f,dcnndvny,squad,human_kunda,FILL_IN
67,5725bbec271a42140099d0d2,dcnndvny,squad,human_kunda,FILL_IN
68,57302efe04bcaa1900d772f7,dcnndvny,squad,human_kunda,FILL_IN
69,572a05eb3f37b31900478653,dcnndvny,squad,human_kunda,FILL_IN
70,570602fa52bb89140068979e,dcnndvny,squad,human_kunda,FILL_IN
71,572f59b4a23a5019007fc58b,dcnndvny,squad,human_kunda,FILL_IN
72,5725b76389a1e219009abd4b,dcnndvny,squad,human_kunda,FILL_IN
73,57060eaf75f01819005e7913,dcnndvny,squad,human_kunda,FILL_IN
74,573749741c4567190057445e,dcnndvny,squad,human_kunda,FILL_IN
75,5727aec03acd2414000de995,dcnndvny,squad,human_kunda,FILL_IN
76,57300c67947a6a140053cff2,dcnndvny,squad,human_kunda,FILL_IN
77,57286192ff5b5019007da1de,dcnndvny,squad,human_kunda,FILL_IN
78,572870b2ff5b5019007da224,dcnndvny,squad,human_kunda,FILL_IN
79,57281c594b864d19001644a5,dcnndvny,squad,human_kunda,FILL_IN
80,57268d2ddd62a815002e8951,dcnndvny,squad,human_kunda,FILL_IN
81,56e202e9e3433e1400423243,dcnndvny,squad,human_kunda,FILL_IN
82,572824f13acd2414000df593,dcnndvny,squad,human_kunda,FILL_IN
83,573081c2069b531400832135,dcnndvny,squad,human_kunda,FILL_IN
84,572863c72ca10214002da2d7,dcnndvny,squad,human_kunda,FILL_IN
85,5728f9882ca10214002dab5c,dcnndvny,squad,human_kunda,FILL_IN
86,57377aac1c4567190057447a,dcnndvny,squad,human_kunda,FILL_IN
87,573786b51c4567190057448f,dcnndvny,squad,human_kunda,FILL_IN
88,57274b35f1498d1400e8f5d4,dcnndvny,squad,human_kunda,FILL_IN
89,57338160d058e614000b5bf9,dcnndvny,squad,human_kunda,FILL_IN
90,57097d63ed30961900e841fd,dcnndvny,squad,human_kunda,FILL_IN
91,571a484210f8ca1400304fbf,dcnndvny,squad,human_kunda,FILL_IN
92,5725f7cd38643c19005acf25,dcnndvny,squad,human_kunda,FILL_IN
93,5725cfd0271a42140099d226,dcnndvny,squad,human_kunda,FILL_IN
94,57264efddd62a815002e8138,dcnndvny,squad,human_kunda,FILL_IN
95,57107d73b654c5140001f91e,dcnndvny,squad,human_kunda,FILL_IN
96,5728661e2ca10214002da2e9,dcnndvny,squad,human_kunda,FILL_IN
97,56e17a7ccd28a01900c679a1,dcnndvny,squad,human_kunda,FILL_IN
98,571c97e2dd7acb1400e4c121,dcnndvny,squad,human_kunda,FILL_IN
99,5726431aec44d21400f3dd13,dcnndvny,squad,human_kunda,FILL_IN

# Load CSV and evaluate agreement

In [19]:
os.getcwd()
# os.chdir("jansen/semantic_uncertainty")

'/auto/users/jansen/semantic_uncertainty'

In [20]:
df = pd.read_csv('notebooks/paper_evals/23-11-24-accuracy-evaluation.csv', index_col=None)

if df.dataset.nunique() > 1:
    raise NotImplementedError('Eval only for one dataset for now')

def remove_incomplete(df):
    # filter out incomplete data!
    ignore = []
    for metric, mdf in df.groupby('truth_metric'):
        if (mdf.truth_value == 'FILL_IN').any():
            ignore.append(metric)
    print(f'Ignoring metrics {ignore} for now.')
    df = df[df.truth_metric.map(lambda x: x not in ignore)]
    return df

df = remove_incomplete(df)

if df.truth_value.nunique() > 2:
    raise ValueError

df

Ignoring metrics [] for now.

,index,data_id,wandb_id,dataset,truth_metric,truth_value
0,0,57338007d058e614000b5bdb,dcnndvny,squad,f1,0
1,1,571cc5c45efbb31900334dde,dcnndvny,squad,f1,1
2,2,5733a5f54776f41900660f46,dcnndvny,squad,f1,0
3,3,5727dd2e4b864d1900163eba,dcnndvny,squad,f1,0
4,4,5733fd66d058e614000b6737,dcnndvny,squad,f1,0
...,...,...,...,...,...,...
595,95,57107d73b654c5140001f91e,uvfbxm6d,squad,llama2,0
596,96,5728661e2ca10214002da2e9,uvfbxm6d,squad,llama2,0
597,97,56e17a7ccd28a01900c679a1,uvfbxm6d,squad,llama2,1
598,98,571c97e2dd7acb1400e4c121,uvfbxm6d,squad,llama2,0
599,99,5726431aec44d21400f3dd13,uvfbxm6d,squad,llama2,0

In [21]:
# compute rater agreement

pdf = df.pivot(index='index', columns='truth_metric', values='truth_value')


def agreement(x, y):
    return np.mean(x == y)

for method in ['pearson', 'kendall', 'spearman', agreement, cohen_kappa_score]:
    print(f'method: {method}')
    display(pdf.corr(method=method))

method: pearson

truth_metric,f1,gpt35,gpt4,human_jansen,human_sebhar,llama2
truth_metric,,,,,,
f1,1.000000,0.099755,0.125916,0.130695,0.135623,0.157129
gpt35,0.099755,1.000000,0.703303,0.770030,0.705290,0.714414
gpt4,0.125916,0.703303,1.000000,0.840692,0.725157,0.722856
human_jansen,0.130695,0.770030,0.840692,1.000000,0.791686,0.838257
human_sebhar,0.135623,0.705290,0.725157,0.791686,1.000000,0.761220
llama2,0.157129,0.714414,0.722856,0.838257,0.761220,1.000000

method: kendall

truth_metric,f1,gpt35,gpt4,human_jansen,human_sebhar,llama2
truth_metric,,,,,,
f1,1.000000,0.099755,0.125916,0.130695,0.135623,0.157129
gpt35,0.099755,1.000000,0.703303,0.770030,0.705290,0.714414
gpt4,0.125916,0.703303,1.000000,0.840692,0.725157,0.722856
human_jansen,0.130695,0.770030,0.840692,1.000000,0.791686,0.838257
human_sebhar,0.135623,0.705290,0.725157,0.791686,1.000000,0.761220
llama2,0.157129,0.714414,0.722856,0.838257,0.761220,1.000000

method: spearman

truth_metric,f1,gpt35,gpt4,human_jansen,human_sebhar,llama2
truth_metric,,,,,,
f1,1.000000,0.099755,0.125916,0.130695,0.135623,0.157129
gpt35,0.099755,1.000000,0.703303,0.770030,0.705290,0.714414
gpt4,0.125916,0.703303,1.000000,0.840692,0.725157,0.722856
human_jansen,0.130695,0.770030,0.840692,1.000000,0.791686,0.838257
human_sebhar,0.135623,0.705290,0.725157,0.791686,1.000000,0.761220
llama2,0.157129,0.714414,0.722856,0.838257,0.761220,1.000000

method: <function agreement at 0x7f2f0cdac7c0>

truth_metric    f1  gpt35  gpt4  human_jansen  human_sebhar  llama2
truth_metric
f1            1.00   0.62  0.68          0.69          0.70    0.74
gpt35         0.62   1.00  0.86          0.89          0.86    0.86
gpt4          0.68   0.86  1.00          0.93          0.88    0.88
human_jansen  0.69   0.89  0.93          1.00          0.91    0.93
human_sebhar  0.70   0.86  0.88          0.91          1.00    0.90
llama2        0.74   0.86  0.88          0.93          0.90    1.00

method: <function cohen_kappa_score at 0x7f2fc9c2bf60>

truth_metric,f1,gpt35,gpt4,human_jansen,human_sebhar,llama2
truth_metric,,,,,,
f1,1.000000,0.041856,0.059377,0.062878,0.066584,0.083862
gpt35,0.041856,1.000000,0.697363,0.761077,0.694457,0.688474
gpt4,0.059377,0.697363,1.000000,0.840474,0.724391,0.715505
human_jansen,0.062878,0.761077,0.840474,1.000000,0.791474,0.832215
human_sebhar,0.066584,0.694457,0.724391,0.791474,1.000000,0.757635
llama2,0.083862,0.688474,0.715505,0.832215,0.757635,1.000000

# Notes

* On Cohen's Cappa from Wikipedia:

> Nonetheless, magnitude guidelines have appeared in the literature. Perhaps the first was Landis and Koch,[16] who characterized values < 0 as indicating no agreement and 0–0.20 as slight, 0.21–0.40 as fair, 0.41–0.60 as moderate, 0.61–0.80 as substantial, and 0.81–1 as almost perfect agreement.

* Squad-f1 completely fails for long generations!

 
## Some thoughts on evaluation:

We are checking  if the answer matches the expected answer, not if the answer is correct!

bad_questions: 

note, that I'm not including underspecified questions 
note, that for these questions, we still just check if the model matches the 'true answer' as given by the data (even if that is wrong)

```
index, data_id, reason, explanation
11, 57300a9a04bcaa1900d77065, 'True Answer Incorrect', "Quote from Wikipedia: 'The Versailles Treaty also stipulated that Allied military forces would withdraw from the Rhineland by 1935.' And in 1936 Germany re-militarized the Rhineland"
```